const router = require('express').Router();
const controller = require('./notes.controller');
const { requireAuth, requireRole } = require('../auth/auth.middleware');
const { upload } = require('./notes.upload');
const { thumbnailUpload } = require('../../utils/thumbnailUpload');
router.get('/', controller.list);
router.get('/admin', requireAuth, requireRole('admin'), controller.adminList);
router.get('/admin/:id', requireAuth, requireRole('admin'), controller.adminDetail);
router.get('/:id', controller.detail);
router.post('/', requireAuth, requireRole('admin'), upload.single('file'), controller.create);
router.post('/:id/thumbnail', requireAuth, requireRole('admin'), thumbnailUpload, controller.uploadThumbnail);
router.delete('/:id/thumbnail', requireAuth, requireRole('admin'), controller.removeThumbnail);
router.patch('/:id', requireAuth, requireRole('admin'), controller.update);
router.delete('/:id', requireAuth, requireRole('admin'), controller.remove);
module.exports = router;
