import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'; import axios from 'axios'; import { AdminStudent, StudentDetail, studentsApiService } from './students.api';
type State = { items: AdminStudent[]; current: StudentDetail | null; loading: boolean; saving: boolean; error: string | null }; const initialState: State = { items: [], current: null, loading: false, saving: false, error: null };
const message = (error: unknown) => axios.isAxiosError(error) ? error.response?.data?.message || 'Student request failed.' : error instanceof Error ? error.message : 'Student request failed.';
export const fetchStudents = createAsyncThunk<AdminStudent[], { search?: string; active?: boolean } | undefined, { rejectValue: string }>('students/list', async (params, api) => { try { return (await studentsApiService.list(params)).data.data; } catch (e) { return api.rejectWithValue(message(e)); } });
export const fetchStudent = createAsyncThunk<StudentDetail, string, { rejectValue: string }>('students/get', async (id, api) => { try { return (await studentsApiService.get(id)).data.data; } catch (e) { return api.rejectWithValue(message(e)); } });
export const updateStudentStatus = createAsyncThunk<AdminStudent, { id: string; isActive: boolean }, { rejectValue: string }>('students/status', async ({ id, isActive }, api) => { try { return (await studentsApiService.updateStatus(id, isActive)).data.data; } catch (e) { return api.rejectWithValue(message(e)); } });
export const grantStudentAccess = createAsyncThunk<StudentDetail, { id: string; type: 'course' | 'test-series'; contentId: string }, { rejectValue: string }>('students/grantAccess', async ({ id, type, contentId }, api) => { try { return (await studentsApiService.grantAccess(id, type, contentId)).data.data; } catch (e) { return api.rejectWithValue(message(e)); } });
export const deleteStudent = createAsyncThunk<string, string, { rejectValue: string }>('students/delete', async (id, api) => { try { await studentsApiService.remove(id); return id; } catch (e) { return api.rejectWithValue(message(e)); } });
const slice = createSlice({ name: 'students', initialState, reducers: {}, extraReducers: (builder) => { builder.addCase(fetchStudents.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchStudents.fulfilled, (state, action) => { state.loading = false; state.items = action.payload; }).addCase(fetchStudents.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load students.'; }); builder.addCase(fetchStudent.pending, (state) => { state.loading = true; state.error = null; state.current = null; }).addCase(fetchStudent.fulfilled, (state, action) => { state.loading = false; state.current = action.payload; }).addCase(fetchStudent.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load student.'; }); builder.addCase(updateStudentStatus.pending, (state) => { state.saving = true; state.error = null; }).addCase(updateStudentStatus.fulfilled, (state, action) => { state.saving = false; const index = state.items.findIndex((item) => item._id === action.payload._id); if (index >= 0) state.items[index] = { ...state.items[index], ...action.payload }; if (state.current?._id === action.payload._id) state.current.isActive = action.payload.isActive; }).addCase(updateStudentStatus.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to update student.'; }); builder.addCase(grantStudentAccess.pending, (state) => { state.saving = true; state.error = null; }).addCase(grantStudentAccess.fulfilled, (state, action) => { state.saving = false; state.current = action.payload; }).addCase(grantStudentAccess.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to grant access.'; }); builder.addCase(deleteStudent.fulfilled, (state, action) => { state.items = state.items.filter((item) => item._id !== action.payload); }).addCase(deleteStudent.rejected, (state, action) => { state.error = action.payload || 'Unable to delete student.'; }); } }); export default slice.reducer;
