import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';
import { AdminNote, CreateNotePayload, NotePayload, noteSchema, notesApiService } from './notes.api';

type State = { items: AdminNote[]; current: AdminNote | null; publicItems: AdminNote[]; loading: boolean; saving: boolean; error: string | null };
const initialState: State = { items: [], current: null, publicItems: [], loading: false, saving: false, error: null };
const message = (error: unknown) => axios.isAxiosError(error) ? error.response?.data?.message || 'Notes request failed.' : error instanceof Error ? error.message : 'Notes request failed.';
export const fetchAdminNotes = createAsyncThunk<AdminNote[], void, { rejectValue: string }>('notes/listAdmin', async (_, api) => { try { return (await notesApiService.listAdmin()).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const fetchAdminNote = createAsyncThunk<AdminNote, string, { rejectValue: string }>('notes/getAdmin', async (id, api) => { try { return (await notesApiService.getAdmin(id)).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const fetchPublicNotes = createAsyncThunk<AdminNote[], void, { rejectValue: string }>('notes/listPublic', async (_, api) => { try { return (await notesApiService.listPublic()).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const createNote = createAsyncThunk<AdminNote, CreateNotePayload, { rejectValue: string }>('notes/create', async (payload, api) => { try { await noteSchema.validate(payload, { abortEarly: false }); return (await notesApiService.create(payload)).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const updateNote = createAsyncThunk<AdminNote, { id: string; payload: NotePayload }, { rejectValue: string }>('notes/update', async ({ id, payload }, api) => { try { await noteSchema.validate(payload, { abortEarly: false }); return (await notesApiService.update(id, payload)).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const uploadNoteThumbnail = createAsyncThunk<AdminNote, { id: string; file: File }, { rejectValue: string }>('notes/uploadThumbnail', async ({ id, file }, api) => { try { return (await notesApiService.uploadThumbnail(id, file)).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const removeNoteThumbnail = createAsyncThunk<AdminNote, string, { rejectValue: string }>('notes/removeThumbnail', async (id, api) => { try { return (await notesApiService.removeThumbnail(id)).data.data.notes; } catch (e) { return api.rejectWithValue(message(e)); } });
export const deleteNote = createAsyncThunk<string, string, { rejectValue: string }>('notes/delete', async (id, api) => { try { await notesApiService.remove(id); return id; } catch (e) { return api.rejectWithValue(message(e)); } });
const slice = createSlice({ name: 'notes', initialState, reducers: { clearNotesError: (state) => { state.error = null; } }, extraReducers: (builder) => {
  builder.addCase(fetchAdminNotes.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchAdminNotes.fulfilled, (state, action) => { state.loading = false; state.items = action.payload; }).addCase(fetchAdminNotes.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load notes.'; });
  builder.addCase(fetchAdminNote.pending, (state) => { state.loading = true; state.error = null; state.current = null; }).addCase(fetchAdminNote.fulfilled, (state, action) => { state.loading = false; state.current = action.payload; }).addCase(fetchAdminNote.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load notes.'; });
  builder.addCase(fetchPublicNotes.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchPublicNotes.fulfilled, (state, action) => { state.loading = false; state.publicItems = action.payload; }).addCase(fetchPublicNotes.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load notes.'; });
  [createNote, updateNote, uploadNoteThumbnail, removeNoteThumbnail].forEach((thunk) => { builder.addCase(thunk.pending, (state) => { state.saving = true; state.error = null; }); builder.addCase(thunk.fulfilled, (state, action) => { state.saving = false; state.current = action.payload; const index = state.items.findIndex((item) => item._id === action.payload._id); if (index >= 0) state.items[index] = action.payload; else state.items.unshift(action.payload); }); builder.addCase(thunk.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to save notes.'; }); });
  builder.addCase(deleteNote.pending, (state) => { state.saving = true; state.error = null; }).addCase(deleteNote.fulfilled, (state, action) => { state.saving = false; state.items = state.items.filter((item) => item._id !== action.payload); }).addCase(deleteNote.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to delete notes.'; });
} });
export const { clearNotesError } = slice.actions;
export default slice.reducer;
