const crypto = require('crypto');
const Razorpay = require('razorpay');
const Course = require('./course.model');
const Enrollment = require('./course.enrollment.model');

function client() { if (!process.env.RAZORPAY_KEY_ID || !process.env.RAZORPAY_KEY_SECRET) throw Object.assign(new Error('Razorpay is not configured.'), { statusCode: 503 }); return new Razorpay({ key_id: process.env.RAZORPAY_KEY_ID, key_secret: process.env.RAZORPAY_KEY_SECRET }); }
async function createOrder(userId, courseId) { const course = await Course.findOne({ _id: courseId, status: 'published' }); if (!course) throw Object.assign(new Error('Course not found.'), { statusCode: 404 }); if (course.access === 'free') { const enrollment = await Enrollment.findOneAndUpdate({ user: userId, course: courseId }, { status: 'active', amount: 0, purchasedAt: new Date() }, { upsert: true, new: true }); return { free: true, enrollment }; } const existing = await Enrollment.findOne({ user: userId, course: courseId, status: 'active' }); if (existing) return { enrolled: true }; const order = await client().orders.create({ amount: Math.round(course.price * 100), currency: 'INR', receipt: `course_${courseId}_${Date.now()}`.slice(0, 40), notes: { courseId: String(courseId), userId: String(userId) } }); await Enrollment.findOneAndUpdate({ user: userId, course: courseId }, { status: 'pending', amount: course.price, currency: 'INR', razorpayOrderId: order.id }, { upsert: true, new: true }); return { order, keyId: process.env.RAZORPAY_KEY_ID, course: { id: course.id, title: course.title } }; }
async function verify(userId, courseId, data) { const expected = crypto.createHmac('sha256', process.env.RAZORPAY_KEY_SECRET || '').update(`${data.razorpay_order_id}|${data.razorpay_payment_id}`).digest('hex'); if (!data.razorpay_signature || expected !== data.razorpay_signature) throw Object.assign(new Error('Payment verification failed.'), { statusCode: 400 }); const enrollment = await Enrollment.findOneAndUpdate({ user: userId, course: courseId, razorpayOrderId: data.razorpay_order_id }, { status: 'active', razorpayPaymentId: data.razorpay_payment_id, purchasedAt: new Date() }, { new: true }); if (!enrollment) throw Object.assign(new Error('Payment order was not found.'), { statusCode: 404 }); return enrollment; }
module.exports = { createOrder, verify };
