const Paper = require('./previousPaper.model');
const Attempt = require('./previousPaper.attempt.model');
const { uploadPdf } = require('./previousPaper.upload');
const { destroy } = require('../../config/cloudinary');
const notifications = require('../notification/notification.service');
async function create(data, file, userId) { const item = new Paper({ ...data, createdBy: userId, pdfUrl: 'pending', pdfPublicId: 'pending' }); Object.assign(item, await uploadPdf(file, item._id.toString())); await item.save(); if (item.status === 'published') await notifications.publish({ title: 'New previous year paper', message: item.title, type: 'previous-paper', href: `/previous-papers/${item._id}`, userId }); return item; }
function publicPaper(item) { return { ...item, questions: (item.questions || []).map(({ correctAnswer, explanation, ...question }) => question) }; }
async function list(admin = false, query = {}) { const filter = admin ? {} : { status: 'published' }; if (query.exam) filter.exam = query.exam; if (query.year) filter.year = Number(query.year); if (query.subject) filter.subject = query.subject; const items = await Paper.find(filter).sort({ year: -1, createdAt: -1 }).lean(); return admin ? items : items.map(publicPaper); }
async function find(id, admin = false) { const item = await Paper.findOne(admin ? { _id: id } : { _id: id, status: 'published' }).lean(); if (!item) throw Object.assign(new Error('Previous year paper not found.'), { statusCode: 404 }); return admin ? item : publicPaper(item); }
async function attempt(id, userId, answers = {}) { const item = await Paper.findOne({ _id: id, status: 'published' }); if (!item) throw Object.assign(new Error('Previous year paper not found.'), { statusCode: 404 }); if (!item.questions.length) throw Object.assign(new Error('Online test is not available for this paper.'), { statusCode: 400 }); let score = 0; let correct = 0; let incorrect = 0; let unanswered = 0; item.questions.forEach((question) => { const answer = answers[question._id.toString()]; if (answer === undefined || answer === null) unanswered += 1; else if (Number(answer) === question.correctAnswer) { correct += 1; score += question.marks; } else { incorrect += 1; score -= question.negativeMarks; } }); const saved = await Attempt.create({ user: userId, paper: id, answers, score, correct, incorrect, unanswered }); return { ...saved.toObject(), title: item.title, totalMarks: item.questions.reduce((total, question) => total + question.marks, 0), questions: item.questions.map((question) => question.toObject()) }; }
async function update(id, data) { const item = await Paper.findByIdAndUpdate(id, data, { new: true, runValidators: true }); if (!item) throw Object.assign(new Error('Previous year paper not found.'), { statusCode: 404 }); return item; }
async function remove(id) { const item = await Paper.findByIdAndDelete(id); if (!item) throw Object.assign(new Error('Previous year paper not found.'), { statusCode: 404 }); await destroy(item.pdfPublicId, 'raw'); }
module.exports = { create, list, find, update, remove, attempt };
