const router = require('express').Router();
const controller = require('./previousPaper.controller');
const { requireAuth, requireRole, optionalAuth } = require('../auth/auth.middleware');
const { upload } = require('./previousPaper.upload');
router.use(optionalAuth);
router.get('/catalog', controller.catalog);
router.patch('/pass-settings', requireAuth, requireRole('admin'), controller.updatePrice);
router.post('/directories', requireAuth, requireRole('admin'), controller.createDirectory);
router.post('/checkout', requireAuth, requireRole('student'), controller.checkout);
router.post('/checkout/verify', requireAuth, requireRole('student'), controller.verifyPayment);
router.get('/', controller.list);
router.get('/admin', requireAuth, requireRole('admin'), controller.adminList);
router.get('/admin/:id', requireAuth, requireRole('admin'), controller.adminDetail);
router.get('/:id', controller.detail);
router.post('/:id/attempts', requireAuth, requireRole('student'), controller.attempt);
router.post('/', requireAuth, requireRole('admin'), upload.single('file'), controller.create);
router.patch('/:id', requireAuth, requireRole('admin'), upload.single('file'), controller.update);
router.delete('/:id', requireAuth, requireRole('admin'), controller.remove);
module.exports = router;
