import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';
import { AdminTestSeries, AttemptResult, PublicTestSeries, SeriesPayload, TestPayload, seriesSchema, testSchema, testSeriesApiService } from './testSeries.api';

type State = { items: AdminTestSeries[]; current: AdminTestSeries | null; publicItems: PublicTestSeries[]; publicCurrent: PublicTestSeries | null; attemptResult: AttemptResult | null; loading: boolean; saving: boolean; error: string | null };
const initialState: State = { items: [], current: null, publicItems: [], publicCurrent: null, attemptResult: null, loading: false, saving: false, error: null };
const message = (error: unknown) => axios.isAxiosError(error) ? error.response?.data?.message || 'Test series request failed.' : error instanceof Error ? error.message : 'Test series request failed.';

export const fetchAdminTestSeries = createAsyncThunk<AdminTestSeries[], void, { rejectValue: string }>('testSeries/listAdmin', async (_, api) => { try { return (await testSeriesApiService.listAdmin()).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const fetchAdminSeries = createAsyncThunk<AdminTestSeries, string, { rejectValue: string }>('testSeries/getAdmin', async (id, api) => { try { return (await testSeriesApiService.getAdmin(id)).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const createTestSeries = createAsyncThunk<AdminTestSeries, SeriesPayload, { rejectValue: string }>('testSeries/create', async (payload, api) => { try { await seriesSchema.validate(payload, { abortEarly: false }); return (await testSeriesApiService.create(payload)).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const updateTestSeries = createAsyncThunk<AdminTestSeries, { id: string; payload: SeriesPayload }, { rejectValue: string }>('testSeries/update', async ({ id, payload }, api) => { try { await seriesSchema.validate(payload, { abortEarly: false }); return (await testSeriesApiService.update(id, payload)).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const deleteTestSeries = createAsyncThunk<string, string, { rejectValue: string }>('testSeries/delete', async (id, api) => { try { await testSeriesApiService.remove(id); return id; } catch (e) { return api.rejectWithValue(message(e)); } });
export const addSeriesTest = createAsyncThunk<AdminTestSeries, { seriesId: string; payload: TestPayload }, { rejectValue: string }>('testSeries/addTest', async ({ seriesId, payload }, api) => { try { await testSchema.validate(payload, { abortEarly: false }); return (await testSeriesApiService.addTest(seriesId, payload)).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const fetchPublicTestSeries = createAsyncThunk<PublicTestSeries[], void, { rejectValue: string }>('testSeries/listPublic', async (_, api) => { try { return (await testSeriesApiService.listPublic()).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const fetchPublicSeries = createAsyncThunk<PublicTestSeries, string, { rejectValue: string }>('testSeries/getPublic', async (id, api) => { try { return (await testSeriesApiService.getPublic(id)).data.data.series; } catch (e) { return api.rejectWithValue(message(e)); } });
export const purchaseTestSeries = createAsyncThunk<void, string, { rejectValue: string }>('testSeries/purchase', async (id, api) => { try { await testSeriesApiService.purchase(id); } catch (e) { return api.rejectWithValue(message(e)); } });
export const submitTestAttempt = createAsyncThunk<AttemptResult, { seriesId: string; testId: string; answers: Record<string, number | null> }, { rejectValue: string }>('testSeries/attempt', async ({ seriesId, testId, answers }, api) => { try { return (await testSeriesApiService.attempt(seriesId, testId, answers)).data.data.result; } catch (e) { return api.rejectWithValue(message(e)); } });

const slice = createSlice({ name: 'testSeries', initialState, reducers: { clearSeriesError: (state) => { state.error = null; } }, extraReducers: (builder) => {
  builder.addCase(fetchAdminTestSeries.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchAdminTestSeries.fulfilled, (state, action) => { state.loading = false; state.items = action.payload; }).addCase(fetchAdminTestSeries.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load test series.'; });
  builder.addCase(fetchAdminSeries.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchAdminSeries.fulfilled, (state, action) => { state.loading = false; state.current = action.payload; }).addCase(fetchAdminSeries.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load test series.'; });
  [createTestSeries, updateTestSeries, addSeriesTest].forEach((thunk) => { builder.addCase(thunk.pending, (state) => { state.saving = true; state.error = null; }); builder.addCase(thunk.fulfilled, (state, action) => { state.saving = false; state.current = action.payload; const index = state.items.findIndex((item) => item._id === action.payload._id); if (index >= 0) state.items[index] = action.payload; else state.items.unshift(action.payload); }); builder.addCase(thunk.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to save test series.'; }); });
  builder.addCase(deleteTestSeries.pending, (state) => { state.saving = true; state.error = null; }).addCase(deleteTestSeries.fulfilled, (state, action) => { state.saving = false; state.items = state.items.filter((item) => item._id !== action.payload); }).addCase(deleteTestSeries.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to delete test series.'; });
  builder.addCase(fetchPublicTestSeries.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchPublicTestSeries.fulfilled, (state, action) => { state.loading = false; state.publicItems = action.payload; }).addCase(fetchPublicTestSeries.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load test series.'; });
  builder.addCase(fetchPublicSeries.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchPublicSeries.fulfilled, (state, action) => { state.loading = false; state.publicCurrent = action.payload; }).addCase(fetchPublicSeries.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load test series.'; });
  builder.addCase(purchaseTestSeries.rejected, (state, action) => { state.error = action.payload || 'Unable to access test series.'; });
  builder.addCase(submitTestAttempt.pending, (state) => { state.saving = true; state.error = null; }).addCase(submitTestAttempt.fulfilled, (state, action) => { state.saving = false; state.attemptResult = action.payload; }).addCase(submitTestAttempt.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to submit test.'; });
} });
export const { clearSeriesError } = slice.actions;
export default slice.reducer;
