const User = require('../auth/auth.model');
const Course = require('../course/course.model');
const Enrollment = require('../course/course.enrollment.model');
const Series = require('../testSeries/testSeries.model');
const Purchase = require('../testSeries/testSeries.purchase.model');
const Attempt = require('../testSeries/testSeries.attempt.model');
const CurrentAffairs = require('../currentAffairs/currentAffairs.model');
const Notes = require('../notes/notes.model');
const Notice = require('../notices/notice.model');

const safeCourse = (course) => ({ _id: course._id, title: course.title, description: course.description, exam: course.exam, category: course.category, instructor: course.instructor, thumbnail: course.thumbnail || '/course-placeholder.svg', access: course.access, price: course.price, lectureCount: course.lectures?.length || 0 });
const safeSeries = (series) => ({ thumbnail: series.thumbnail || '', _id: series._id, title: series.title, description: series.description, exam: series.exam, access: series.access, price: series.price, difficulty: series.difficulty, languages: series.languages, testCount: series.tests?.filter((test) => test.status === 'published').length || 0, questionCount: (series.tests || []).reduce((sum, test) => sum + (test.status === 'published' ? test.questions.length : 0), 0) });

async function home() { const [students, courses, series, currentAffairs, categories] = await Promise.all([User.countDocuments({ role: 'student', isActive: true }), Course.find({ status: 'published' }).sort({ publishedAt: -1 }).limit(4).lean(), Series.find({ status: 'published' }).sort({ createdAt: -1 }).limit(4).lean(), CurrentAffairs.findOne({ status: 'published' }).sort({ date: -1 }).lean(), Course.aggregate([{ $match: { status: 'published' } }, { $group: { _id: '$category', resources: { $sum: 1 } } }, { $sort: { resources: -1 } }, { $limit: 8 }])]); const testCount = series.reduce((sum, item) => sum + item.tests.filter((test) => test.status === 'published').length, 0); const questionCount = series.reduce((sum, item) => sum + item.tests.reduce((total, test) => total + (test.status === 'published' ? test.questions.length : 0), 0), 0); return { stats: { students, tests: testCount, questions: questionCount }, categories: categories.map((item) => ({ name: item._id, resources: item.resources })), courses: courses.map(safeCourse), testSeries: series.map(safeSeries), currentAffairs: currentAffairs ? { _id: currentAffairs._id, title: currentAffairs.title, date: currentAffairs.date, highlights: currentAffairs.highlights, pdfUrl: currentAffairs.pdfUrl, exam: currentAffairs.exam, questionCount: currentAffairs.questions.length } : null }; }
async function student(userId) { const [enrollments, purchases, attempts, currentAffairs] = await Promise.all([Enrollment.find({ user: userId, status: 'active' }).populate('course').sort({ updatedAt: -1 }).lean(), Purchase.find({ user: userId, status: 'active' }).populate('series').lean(), Attempt.find({ user: userId }).sort({ submittedAt: -1 }).limit(5).lean(), CurrentAffairs.findOne({ status: 'published' }).sort({ date: -1 }).lean()]); const attempted = await Attempt.countDocuments({ user: userId }); const accuracy = attempts.length ? Math.round(attempts.reduce((sum, item) => sum + item.accuracy, 0) / attempts.length) : 0; return { stats: { courses: enrollments.length, testSeries: purchases.length, attempts: attempted, averageAccuracy: accuracy }, courses: enrollments.filter((item) => item.course).map((item) => ({ ...safeCourse(item.course), enrolledAt: item.purchasedAt || item.createdAt })), recentResults: attempts, currentAffairs: currentAffairs ? { _id: currentAffairs._id, title: currentAffairs.title, date: currentAffairs.date, questionCount: currentAffairs.questions.length } : null }; }
async function admin() { const [students, courses, drafts, series, notes, notices, attempts, recentStudents] = await Promise.all([User.countDocuments({ role: 'student' }), Course.countDocuments(), Course.countDocuments({ status: 'draft' }), Series.find().lean(), Notes.countDocuments(), Notice.countDocuments(), Attempt.countDocuments(), User.find({ role: 'student' }).sort({ createdAt: -1 }).limit(6).lean()]); return { stats: { students, courses, courseDrafts: drafts, testSeries: series.length, tests: series.reduce((sum, item) => sum + item.tests.length, 0), questions: series.reduce((sum, item) => sum + item.tests.reduce((total, test) => total + test.questions.length, 0), 0), attempts, notes, notices }, recentActivity: recentStudents.map((user) => ({ id: user._id, text: `${user.name} registered as a student`, date: user.createdAt })) }; }
module.exports = { home, student, admin };
