import axios from 'axios';
import * as yup from 'yup';
export type PaperStatus = 'draft' | 'published' | 'unpublished';
export interface PaperQuestion { _id?: string; text: string; options: string[]; correctAnswer: number; explanation: string; marks: number; negativeMarks: number }
export interface PublicPaperQuestion extends Omit<PaperQuestion, 'correctAnswer' | 'explanation'> { _id: string; correctAnswer?: number; explanation?: string }
export interface PublicPreviousPaper extends Omit<AdminPreviousPaper, 'questions'> { questions: PublicPaperQuestion[] }
export interface PreviousPaperAttempt { _id: string; paper: string; title: string; answers: Record<string, number>; score: number; correct: number; incorrect: number; unanswered: number; totalMarks: number; questions: PaperQuestion[] }
export interface AdminPreviousPaper { _id: string; title: string; exam: string; year: number; stage: string; shift: string; subject: string; pdfUrl: string; duration: number; questions: PaperQuestion[]; status: PaperStatus; createdAt: string; updatedAt: string }
export interface PaperPayload { title: string; exam: string; year: number; stage: string; shift: string; subject: string; duration: number; questions: PaperQuestion[]; status: PaperStatus }
export interface CreatePaperPayload extends PaperPayload { file: File }
export const paperSchema = yup.object({ title: yup.string().trim().required('Title is required.'), exam: yup.string().trim().required('Exam is required.'), year: yup.number().integer().min(1950).required(), stage: yup.string().trim().required('Stage is required.'), shift: yup.string().trim().default(''), subject: yup.string().trim().required(), duration: yup.number().min(0).required(), questions: yup.array().of(yup.object({ text: yup.string().trim().required(), options: yup.array().of(yup.string().trim().required()).min(2).required(), correctAnswer: yup.number().integer().min(0).required(), explanation: yup.string().default(''), marks: yup.number().min(0).required(), negativeMarks: yup.number().min(0).required() })).required(), status: yup.mixed<PaperStatus>().oneOf(['draft', 'published', 'unpublished']).required() });
const api = axios.create({ baseURL: import.meta.env.VITE_API_URL, withCredentials: true });
export const previousPapersApiService = { listPublic: () => api.get('/previous-papers'), getPublic: (id: string) => api.get(`/previous-papers/${id}`), attempt: (id: string, answers: Record<string, number | null>) => api.post(`/previous-papers/${id}/attempts`, { answers }), listAdmin: () => api.get('/previous-papers/admin'), getAdmin: (id: string) => api.get(`/previous-papers/admin/${id}`), create: (payload: CreatePaperPayload) => { const data = new FormData(); ['title', 'exam', 'stage', 'shift', 'subject', 'status'].forEach((key) => data.append(key, String(payload[key as keyof PaperPayload] ?? ''))); data.append('year', String(payload.year)); data.append('duration', String(payload.duration)); data.append('questions', JSON.stringify(payload.questions)); data.append('file', payload.file, payload.file.name); return api.post('/previous-papers', data); }, update: (id: string, payload: PaperPayload) => api.patch(`/previous-papers/${id}`, payload), remove: (id: string) => api.delete(`/previous-papers/${id}`) };
