import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';
import { AdminSyllabusDocument, CreateSyllabusPayload, SyllabusPayload, syllabusApiService, syllabusSchema } from './syllabus.api';

type State = { items: AdminSyllabusDocument[]; current: AdminSyllabusDocument | null; publicItems: AdminSyllabusDocument[]; loading: boolean; saving: boolean; error: string | null };
const initialState: State = { items: [], current: null, publicItems: [], loading: false, saving: false, error: null };
const message = (error: unknown) => axios.isAxiosError(error) ? error.response?.data?.message || 'Syllabus request failed.' : error instanceof Error ? error.message : 'Syllabus request failed.';

export const fetchPublicSyllabus = createAsyncThunk<AdminSyllabusDocument[], void, { rejectValue: string }>('syllabus/listPublic', async (_, api) => { try { return (await syllabusApiService.listPublic()).data.data.syllabus; } catch (error) { return api.rejectWithValue(message(error)); } });
export const fetchAdminSyllabus = createAsyncThunk<AdminSyllabusDocument[], void, { rejectValue: string }>('syllabus/listAdmin', async (_, api) => { try { return (await syllabusApiService.listAdmin()).data.data.syllabus; } catch (error) { return api.rejectWithValue(message(error)); } });
export const fetchAdminSyllabusDocument = createAsyncThunk<AdminSyllabusDocument, string, { rejectValue: string }>('syllabus/getAdmin', async (id, api) => { try { return (await syllabusApiService.getAdmin(id)).data.data.syllabus; } catch (error) { return api.rejectWithValue(message(error)); } });
export const createSyllabus = createAsyncThunk<AdminSyllabusDocument, CreateSyllabusPayload, { rejectValue: string }>('syllabus/create', async (payload, api) => { try { await syllabusSchema.validate(payload, { abortEarly: false }); return (await syllabusApiService.create(payload)).data.data.syllabus; } catch (error) { return api.rejectWithValue(message(error)); } });
export const updateSyllabus = createAsyncThunk<AdminSyllabusDocument, { id: string; payload: SyllabusPayload }, { rejectValue: string }>('syllabus/update', async ({ id, payload }, api) => { try { await syllabusSchema.validate(payload, { abortEarly: false }); return (await syllabusApiService.update(id, payload)).data.data.syllabus; } catch (error) { return api.rejectWithValue(message(error)); } });
export const deleteSyllabus = createAsyncThunk<string, string, { rejectValue: string }>('syllabus/delete', async (id, api) => { try { await syllabusApiService.remove(id); return id; } catch (error) { return api.rejectWithValue(message(error)); } });

const slice = createSlice({ name: 'syllabus', initialState, reducers: {}, extraReducers: (builder) => {
  builder.addCase(fetchPublicSyllabus.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchPublicSyllabus.fulfilled, (state, action) => { state.loading = false; state.publicItems = action.payload; }).addCase(fetchPublicSyllabus.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load syllabus.'; });
  builder.addCase(fetchAdminSyllabus.pending, (state) => { state.loading = true; state.error = null; }).addCase(fetchAdminSyllabus.fulfilled, (state, action) => { state.loading = false; state.items = action.payload; }).addCase(fetchAdminSyllabus.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load syllabus.'; });
  builder.addCase(fetchAdminSyllabusDocument.pending, (state) => { state.loading = true; state.error = null; state.current = null; }).addCase(fetchAdminSyllabusDocument.fulfilled, (state, action) => { state.loading = false; state.current = action.payload; }).addCase(fetchAdminSyllabusDocument.rejected, (state, action) => { state.loading = false; state.error = action.payload || 'Unable to load syllabus.'; });
  [createSyllabus, updateSyllabus].forEach((thunk) => { builder.addCase(thunk.pending, (state) => { state.saving = true; state.error = null; }); builder.addCase(thunk.fulfilled, (state, action) => { state.saving = false; state.current = action.payload; const index = state.items.findIndex((item) => item._id === action.payload._id); if (index >= 0) state.items[index] = action.payload; else state.items.unshift(action.payload); }); builder.addCase(thunk.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to save syllabus.'; }); });
  builder.addCase(deleteSyllabus.pending, (state) => { state.saving = true; state.error = null; }).addCase(deleteSyllabus.fulfilled, (state, action) => { state.saving = false; state.items = state.items.filter((item) => item._id !== action.payload); }).addCase(deleteSyllabus.rejected, (state, action) => { state.saving = false; state.error = action.payload || 'Unable to delete syllabus.'; });
} });
export default slice.reducer;
