import React, { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link, useParams } from 'react-router-dom';
import { PageShell, Panel } from '../components/ui/PageShell';
import { Button, btn } from '../components/ui/Primitives';
import { fetchPublicCurrentAffairs, submitCurrentAffairsAttempt } from '../services/current-affairs/currentAffairs.slice';
import type { AppDispatch, RootState } from '../store';

export function CurrentAffairsTest() {
  const { entryId = '' } = useParams(); const dispatch = useDispatch<AppDispatch>();
  const { publicItems, loading, saving, error, attemptResult } = useSelector((state: RootState) => state.currentAffairs);
  const [answers, setAnswers] = useState<Record<string, number | null>>({});
  useEffect(() => { if (!publicItems.length) dispatch(fetchPublicCurrentAffairs()); }, [dispatch, publicItems.length]);
  const entry = publicItems.find((item) => item._id === entryId); const result = attemptResult?.currentAffairs === entryId ? attemptResult : null;
  if (loading && !entry) return <PageShell title="Daily Test"><p className="py-12 text-center text-sm text-ink-muted">Loading test...</p></PageShell>;
  if (!entry) return <PageShell title="Test not found"><p className="mb-5 text-sm text-red-600">{error || 'This current affairs test is unavailable.'}</p><Link to="/current-affairs" className={btn('primary', 'md')}>Back to Current Affairs</Link></PageShell>;
  const submit = async () => { try { await dispatch(submitCurrentAffairsAttempt({ id: entryId, answers })).unwrap(); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch { /* Redux displays the API error. */ } };
  return <PageShell width="max-w-4xl"><nav className="mb-5 text-sm text-ink-muted"><Link to="/current-affairs" className="hover:text-brand-700">Current Affairs</Link><span className="mx-2">/</span><span>Daily Test</span></nav>
    <div className="mb-6"><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">Daily current affairs test</p><h1 className="mt-2 text-2xl font-bold text-ink">{entry.title}</h1><p className="mt-1 text-sm text-ink-muted">{entry.questions.length} questions · {new Date(entry.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p></div>
    {result ? <><div className="grid grid-cols-3 gap-3">{[['Score', `${result.score}/${result.questions.length}`], ['Correct', result.correct], ['Incorrect', result.incorrect]].map(([label, value]) => <div key={label} className="rounded-xl border border-line bg-white p-4 text-center"><p className="text-xs text-ink-muted">{label}</p><p className="mt-1 text-xl font-bold text-ink">{value}</p></div>)}</div><div className="mt-6 space-y-4">{result.questions.map((question, index) => { const chosen = result.answers[question._id || '']; return <Panel key={question._id}><p className="font-medium text-ink">{index + 1}. {question.text}</p><div className="mt-3 space-y-2">{question.options.map((option, optionIndex) => <div key={optionIndex} className={`rounded-lg border p-3 text-sm ${optionIndex === question.correctAnswer ? 'border-emerald-300 bg-emerald-50' : optionIndex === chosen ? 'border-red-300 bg-red-50' : 'border-line'}`}>{String.fromCharCode(65 + optionIndex)}. {option}</div>)}</div>{question.explanation && <p className="mt-3 text-sm text-ink-soft"><strong className="text-ink">Explanation:</strong> {question.explanation}</p>}</Panel>; })}</div></> : <><div className="space-y-4">{entry.questions.map((question, index) => <Panel key={question._id}><fieldset><legend className="font-medium leading-6 text-ink">{index + 1}. {question.text}</legend><div className="mt-4 grid gap-2">{question.options.map((option, optionIndex) => <label key={optionIndex} className={`cursor-pointer rounded-xl border p-3 text-sm ${answers[question._id] === optionIndex ? 'border-brand-600 bg-brand-50' : 'border-line hover:bg-canvas'}`}><input type="radio" className="mr-3" name={question._id} checked={answers[question._id] === optionIndex} onChange={() => setAnswers((current) => ({ ...current, [question._id]: optionIndex }))} />{option}</label>)}</div></fieldset></Panel>)}</div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<Button disabled={saving || !entry.questions.length} onClick={submit} className="mt-6 w-full">{saving ? 'Submitting...' : 'Submit Test'}</Button></>}
  </PageShell>;
}
