import { CourseThumbnail } from '../components/courses/CourseThumbnail';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { BookOpenIcon, CalendarDaysIcon, ListChecksIcon, TargetIcon } from 'lucide-react';
import { PageShell, Panel, StatCard } from '../components/ui/PageShell';
import { EmptyState, btn } from '../components/ui/Primitives';
import { fetchStudentDashboard } from '../services/dashboard/dashboard.slice';
import type { AppDispatch, RootState } from '../store';
import { BannerCarousel } from '../components/marketing/BannerCarousel';
export function Dashboard() { const dispatch = useDispatch<AppDispatch>(); const { student: data, loading, error } = useSelector((s: RootState) => s.dashboard); const user = useSelector((s: RootState) => s.auth.user); useEffect(() => { if (user?.role === 'student') dispatch(fetchStudentDashboard()); }, [dispatch, user]); if (loading && !data) return <PageShell title="Dashboard"><Panel><p>Loading dashboard...</p></Panel></PageShell>; return <PageShell title={`Welcome${user ? `, ${user.name.split(' ')[0]}` : ''}`} subtitle="Continue your preparation today." actions={<Link to="/current-affairs" className={btn('secondary', 'md')}><CalendarDaysIcon className="h-4 w-4" /> Current affairs</Link>}><BannerCarousel placement="dashboard" /><div className="mt-5">{error && <p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Courses enrolled" value={String(data?.stats?.courses || 0)} icon={<BookOpenIcon className="h-4 w-4" />} /><StatCard label="Test series" value={String(data?.stats?.testSeries || 0)} icon={<ListChecksIcon className="h-4 w-4" />} /><StatCard label="Tests attempted" value={String(data?.stats?.attempts || 0)} icon={<ListChecksIcon className="h-4 w-4" />} /><StatCard label="Average accuracy" value={`${data?.stats?.averageAccuracy || 0}%`} icon={<TargetIcon className="h-4 w-4" />} /></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><div className="flex justify-between"><h2 className="font-semibold text-ink">My courses</h2><Link to="/courses" className="text-sm text-brand-700">All courses</Link></div><div className="mt-4 space-y-3">{!data?.courses?.length ? <EmptyState icon={<BookOpenIcon className="h-5 w-5" />} title="No enrolled courses." description="Enroll in a free course or purchase a course to begin." /> : data.courses.map((course: any) => <Link key={course._id} to={`/courses/${course._id}`} className="flex items-center gap-3 rounded-xl border border-line p-3 hover:bg-canvas"><CourseThumbnail src={course.thumbnail} alt={course.title} className="h-14 w-20 rounded-lg object-cover" /><div><p className="text-sm font-semibold text-ink">{course.title}</p><p className="text-xs text-ink-muted">{course.lectureCount} lectures</p></div></Link>)}</div></Panel><Panel><h2 className="font-semibold text-ink">Recent results</h2><div className="mt-4 space-y-2">{!data?.recentResults?.length ? <p className="text-sm text-ink-muted">No test attempts yet.</p> : data.recentResults.map((result: any) => <div key={result._id} className="flex justify-between rounded-xl border border-line p-3 text-sm"><span className="text-ink">Test attempt</span><span className="font-semibold text-ink">{result.score} · {result.accuracy}%</span></div>)}</div></Panel></div></div></PageShell>; }
