import { TestSeriesThumbnail } from '../components/courses/TestSeriesThumbnail';
import { CourseThumbnail } from '../components/courses/CourseThumbnail';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { BookOpenIcon, FileTextIcon, ListChecksIcon, MailIcon, MapPinIcon, PhoneIcon } from 'lucide-react';
import { Badge, SectionHeading, btn } from '../components/ui/Primitives';
import { HeroDashboard } from '../components/marketing/HeroDashboard';
import { useViewer } from '../contexts/ViewerContext';
import { fetchHomeDashboard } from '../services/dashboard/dashboard.slice';
import type { AppDispatch, RootState } from '../store';

export function Home() {
  const dispatch = useDispatch<AppDispatch>(); const { home: data, loading, error } = useSelector((s: RootState) => s.dashboard); const { openPdf } = useViewer(); useEffect(() => { dispatch(fetchHomeDashboard()); }, [dispatch]); const stats = data?.stats || {}; const content = data?.content || {}; const current = data?.currentAffairs;
  return <div className="bg-white"><section className="border-b border-line"><div className="mx-auto grid w-full max-w-none items-center gap-10 px-4 py-14 sm:px-6 lg:grid-cols-2 lg:px-6 lg:py-20"><div><Badge tone="brand">Complete exam preparation</Badge><h1 className="mt-4 text-4xl font-extrabold leading-tight text-ink sm:text-5xl">Prepare Smarter.<br />Learn Better.<br /><span className="text-brand-600">Score Higher.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-ink-soft">Courses, test series, notes, current affairs and previous year papers—all organized in one simple learning platform.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/courses" className={btn('primary','lg')}>Explore Courses</Link><Link to="/test-series" className={btn('secondary','lg')}>Take a Test</Link></div><dl className="mt-10 grid max-w-sm grid-cols-2 gap-8 border-t border-line pt-7"><div><dt className="text-3xl font-bold text-ink">{Number(stats.tests || 0).toLocaleString('en-IN')}</dt><dd className="text-sm text-ink-soft">Mock tests</dd></div><div><dt className="text-3xl font-bold text-ink">{Number(stats.questions || 0).toLocaleString('en-IN')}</dt><dd className="text-sm text-ink-soft">Questions</dd></div></dl></div><HeroDashboard /></div></section>{error && <p className="mx-auto mt-5 w-full max-w-none rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <section className="mx-auto w-full max-w-none px-4 py-14 sm:px-6 lg:px-6"><SectionHeading title="Popular categories" subtitle="Choose a focused preparation path." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(data?.categories || []).map((item: any) => <Link key={item.name} to={`/courses?category=${encodeURIComponent(item.name)}`} className="rounded-2xl border border-line p-5 hover:border-brand-300 hover:bg-brand-50"><BookOpenIcon className="h-5 w-5 text-brand-600" /><p className="mt-3 font-semibold text-ink">{item.name}</p><p className="text-xs text-ink-muted">{item.resources} resources</p></Link>)}</div></section>
    <section className="border-y border-line bg-canvas"><div className="mx-auto w-full max-w-none px-4 py-14 sm:px-6 lg:px-6"><SectionHeading title="Featured courses" action={<Link to="/courses" className={btn('secondary','sm')}>View all</Link>} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{loading ? <p className="text-sm text-ink-muted">Loading...</p> : (data?.courses || []).map((course: any) => <Link key={course._id} to={`/courses/${course._id}`} className="overflow-hidden rounded-2xl border border-line bg-white hover:shadow-soft"><CourseThumbnail src={course.thumbnail} alt={course.title} className="h-36 w-full sm:h-40 object-cover" /><div className="p-4"><Badge tone={course.access === 'free' ? 'green' : 'violet'}>{course.access}</Badge><h2 className="mt-2 font-semibold text-ink">{course.title}</h2><p className="mt-2 line-clamp-2 text-sm text-ink-soft">{course.description}</p><p className="mt-3 text-xs text-ink-muted">{course.lectureCount} lectures</p></div></Link>)}</div></div></section>
    <section className="mx-auto w-full max-w-none px-4 py-14 sm:px-6 lg:px-6"><SectionHeading title="Popular test series" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(data?.testSeries || []).map((series: any) => <Link key={series._id} to={`/test-series/${series._id}`} className="rounded-2xl border border-line p-4 hover:shadow-soft">{series.thumbnail ? <TestSeriesThumbnail src={series.thumbnail} alt={series.title} className="h-36 w-full sm:h-40 rounded-xl object-cover" /> : <ListChecksIcon className="h-6 w-6 text-brand-600" />}<h2 className="mt-3 font-semibold text-ink">{series.title}</h2><p className="mt-2 text-sm text-ink-soft">{series.testCount} tests · {series.questionCount} questions</p></Link>)}</div></section>
    {current && <section className="border-y border-line bg-canvas"><div className="mx-auto w-full max-w-none px-4 py-14 sm:px-6 lg:px-6"><SectionHeading title="Latest current affairs" /><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-line bg-white p-6"><h2 className="font-semibold text-ink">{current.title}</h2><ul className="mt-4 space-y-2">{current.highlights.slice(0,4).map((item: string) => <li key={item} className="text-sm text-ink-soft">• {item}</li>)}</ul><Link to={`/current-affairs/${current._id}/test`} className={btn('primary','sm','mt-5')}>Take Daily Test</Link></div><div className="rounded-2xl border border-line bg-white p-6"><FileTextIcon className="h-6 w-6 text-red-500" /><h2 className="mt-3 font-semibold text-ink">Daily Current Affairs PDF</h2><button onClick={() => openPdf({ title: current.title, subtitle: current.exam, module: 'current-affairs', url: current.pdfUrl, pages: [] })} className={btn('secondary','md','mt-5 w-full')}>Read PDF</button></div></div></div></section>}
    <section id="about" className="mx-auto w-full max-w-none px-4 py-16 sm:px-6 lg:px-6"><div className="grid gap-8 rounded-3xl bg-brand-50 p-7 sm:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><Badge tone="brand">About us</Badge><h2 className="mt-4 text-3xl font-bold text-ink">{content.aboutTitle}</h2></div><p className="whitespace-pre-line text-base leading-8 text-ink-soft">{content.aboutDescription}</p></div></section>
    <section id="contact" className="border-t border-line bg-canvas"><div className="mx-auto w-full max-w-none px-4 py-16 sm:px-6 lg:px-6"><SectionHeading title="Contact us" subtitle="Need help with your preparation or account? Reach our team." /><div className="grid gap-4 sm:grid-cols-3">{content.contactEmail && <a href={`mailto:${content.contactEmail}`} className="rounded-2xl border border-line bg-white p-5"><MailIcon className="h-5 w-5 text-brand-600" /><p className="mt-3 text-xs text-ink-muted">Email</p><p className="mt-1 font-semibold text-ink">{content.contactEmail}</p></a>}{content.contactPhone && <a href={`tel:${content.contactPhone}`} className="rounded-2xl border border-line bg-white p-5"><PhoneIcon className="h-5 w-5 text-brand-600" /><p className="mt-3 text-xs text-ink-muted">Phone</p><p className="mt-1 font-semibold text-ink">{content.contactPhone}</p></a>}{content.contactAddress && <div className="rounded-2xl border border-line bg-white p-5"><MapPinIcon className="h-5 w-5 text-brand-600" /><p className="mt-3 text-xs text-ink-muted">Address</p><p className="mt-1 font-semibold text-ink">{content.contactAddress}</p></div>}</div></div></section>
  </div>;
}
