import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link, useParams } from 'react-router-dom';
import { PageShell, Panel } from '../components/ui/PageShell';
import { Button, btn } from '../components/ui/Primitives';
import { fetchPublicPreviousPapers, submitPreviousPaperAttempt } from '../services/previous-papers/previousPapers.slice';
import type { AppDispatch, RootState } from '../store';

export function PreviousPaperTest() {
  const { paperId = '' } = useParams(); const dispatch = useDispatch<AppDispatch>(); const { publicItems, attemptResult, loading, saving, error } = useSelector((state: RootState) => state.previousPapers); const [answers, setAnswers] = useState<Record<string, number | null>>({});
  useEffect(() => { if (!publicItems.length) dispatch(fetchPublicPreviousPapers()); }, [dispatch, publicItems.length]);
  const paper = publicItems.find((item) => item._id === paperId); const result = attemptResult?.paper === paperId ? attemptResult : null;
  if (loading && !paper) return <PageShell title="Previous Paper Test"><p className="py-12 text-center text-sm text-ink-muted">Loading test...</p></PageShell>;
  if (!paper) return <PageShell title="Test not found"><p className="mb-5 text-sm text-red-600">{error || 'This paper is unavailable.'}</p><Link to="/previous-papers" className={btn('primary', 'md')}>Back to Papers</Link></PageShell>;
  const submit = async () => { try { await dispatch(submitPreviousPaperAttempt({ id: paperId, answers })).unwrap(); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch { /* Redux displays API error. */ } };
  return <PageShell width="max-w-4xl"><nav className="mb-5 text-sm text-ink-muted"><Link to="/previous-papers" className="hover:text-brand-700">Previous Papers</Link><span className="mx-2">/</span><span>Online Test</span></nav><h1 className="text-2xl font-bold text-ink">{paper.title}</h1><p className="mt-2 text-sm text-ink-muted">{paper.questions.length} questions · {paper.duration || 'No time limit'}{paper.duration ? ' minutes' : ''}</p>
    {result ? <><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Score', `${result.score}/${result.totalMarks}`], ['Correct', result.correct], ['Incorrect', result.incorrect], ['Skipped', result.unanswered]].map(([label, value]) => <div key={label} className="rounded-xl border border-line bg-white p-4 text-center"><p className="text-xs text-ink-muted">{label}</p><p className="mt-1 text-xl font-bold text-ink">{value}</p></div>)}</div><div className="mt-6 space-y-4">{result.questions.map((question, index) => { const selected = result.answers[question._id || '']; return <Panel key={question._id}><p className="font-medium text-ink">{index + 1}. {question.text}</p><div className="mt-3 space-y-2">{question.options.map((option, optionIndex) => <div key={optionIndex} className={`rounded-lg border p-3 text-sm ${optionIndex === question.correctAnswer ? 'border-emerald-300 bg-emerald-50' : optionIndex === selected ? 'border-red-300 bg-red-50' : 'border-line'}`}>{String.fromCharCode(65 + optionIndex)}. {option}</div>)}</div>{question.explanation && <p className="mt-3 text-sm text-ink-soft"><strong className="text-ink">Explanation:</strong> {question.explanation}</p>}</Panel>; })}</div></> : <><div className="mt-6 space-y-4">{paper.questions.map((question, index) => <Panel key={question._id}><fieldset><legend className="font-medium leading-6 text-ink">{index + 1}. {question.text}</legend><div className="mt-4 grid gap-2">{question.options.map((option, optionIndex) => <label key={optionIndex} className={`cursor-pointer rounded-xl border p-3 text-sm ${answers[question._id] === optionIndex ? 'border-brand-600 bg-brand-50' : 'border-line hover:bg-canvas'}`}><input type="radio" name={question._id} className="mr-3" checked={answers[question._id] === optionIndex} onChange={() => setAnswers((current) => ({ ...current, [question._id]: optionIndex }))} />{option}</label>)}</div></fieldset></Panel>)}</div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<Button disabled={saving} onClick={submit} className="mt-6 w-full">{saving ? 'Submitting...' : 'Submit Paper'}</Button></>}
  </PageShell>;
}
