import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { CheckCircle2Icon, CheckIcon, ChevronLeftIcon, ChevronRightIcon, FileTextIcon, ListIcon, LockIcon, PlayIcon, XIcon } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { Badge, btn } from '../components/ui/Primitives';
import { Logo } from '../components/layout/Logo';
import { fetchPublicCourse } from '../services/courses/courses.slice';
import type { AppDispatch, RootState } from '../store';

export function VideoViewer() {
  const { courseId = '', lessonId = '' } = useParams(); const dispatch = useDispatch<AppDispatch>(); const navigate = useNavigate();
  const { publicCurrent, loading } = useSelector((state: RootState) => state.courses); const [completed, setCompleted] = useState<string[]>([]); const [playlistOpen, setPlaylistOpen] = useState(false);
  useEffect(() => { if (courseId) dispatch(fetchPublicCourse(courseId)); }, [courseId, dispatch]);
  const course = publicCurrent?._id === courseId ? publicCurrent : null;
  const playable = useMemo(() => course?.lectures.filter((lecture) => Boolean(lecture.url)) || [], [course]);
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-canvas"><p className="text-sm text-ink-muted">Loading lecture...</p></div>;
  if (!course) return <div className="flex min-h-screen items-center justify-center bg-canvas"><Link to="/courses" className={btn('primary', 'md')}>Back to courses</Link></div>;
  const lesson = course.lectures.find((lecture) => lecture._id === lessonId); if (!lesson || !lesson.url) return <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-canvas"><LockIcon className="h-8 w-8 text-ink-muted" /><p className="text-sm text-ink-soft">This lecture is not available with your current access.</p><Link to={`/courses/${course._id}`} className={btn('primary', 'md')}>Back to course</Link></div>;
  const index = playable.findIndex((item) => item._id === lesson._id); const previous = playable[index - 1]; const next = playable[index + 1]; const done = completed.includes(lesson._id);
  const playlist = <div className="flex h-full flex-col"><div className="flex items-center justify-between border-b border-line px-4 py-3.5"><div><p className="text-sm font-semibold text-ink">Course lectures</p><p className="text-xs text-ink-muted">{course.lectures.length} lectures</p></div><button onClick={() => setPlaylistOpen(false)} className="flex h-8 w-8 items-center justify-center rounded-lg text-ink-muted lg:hidden"><XIcon className="h-4 w-4" /></button></div><div className="flex-1 overflow-y-auto p-2">{course.lectures.map((item, itemIndex) => item.url ? <Link key={item._id} to={`/learn/${course._id}/${item._id}`} onClick={() => setPlaylistOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 ${item._id === lesson._id ? 'bg-brand-50' : 'hover:bg-canvas'}`}>{completed.includes(item._id) ? <CheckCircle2Icon className="h-4 w-4 text-emerald-500" /> : <PlayIcon className="h-4 w-4 text-brand-600" />}<span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-medium text-ink">{itemIndex + 1}. {item.title}</span><span className="block truncate text-[11px] text-ink-muted">{item.duration || 'Video lecture'}</span></span></Link> : <div key={item._id} className="flex items-center gap-3 px-3 py-3 text-ink-muted"><LockIcon className="h-4 w-4" /><span className="truncate text-[13px]">{itemIndex + 1}. {item.title}</span></div>)}</div></div>;
  return <div className="flex min-h-screen w-full flex-col bg-canvas"><header className="sticky top-0 z-40 flex h-16 items-center gap-3 border-b border-line bg-white px-4 sm:px-6"><Logo /><div className="ml-2 hidden min-w-0 border-l border-line pl-4 sm:block"><p className="truncate text-[13px] font-semibold text-ink">{course.title}</p><p className="truncate text-xs text-ink-muted">{lesson.title}</p></div><div className="ml-auto flex gap-2"><button onClick={() => setPlaylistOpen(true)} className={btn('secondary', 'sm', 'lg:hidden')}><ListIcon className="h-4 w-4" /> Lectures</button><Link to={`/courses/${course._id}`} className={btn('secondary', 'sm')}>Course page</Link></div></header>
    <div className="mx-auto grid w-full max-w-7xl flex-1 gap-5 px-4 py-5 sm:px-6 lg:grid-cols-[1.7fr_360px] lg:px-8"><div><div className="overflow-hidden rounded-2xl bg-black"><video key={lesson.url} src={lesson.url} controls controlsList="nodownload" disablePictureInPicture onContextMenu={(event) => event.preventDefault()} className="aspect-video w-full" /></div><div className="mt-5 rounded-2xl border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone="brand">Lecture {course.lectures.findIndex((item) => item._id === lesson._id) + 1}</Badge><h1 className="mt-2.5 text-xl font-bold text-ink">{lesson.title}</h1></div><button onClick={() => setCompleted((items) => items.includes(lesson._id) ? items : [...items, lesson._id])} className={btn(done ? 'secondary' : 'primary', 'md')}>{done ? <><CheckIcon className="h-4 w-4" /> Completed</> : 'Mark as completed'}</button></div><p className="mt-3 text-sm leading-6 text-ink-soft">{lesson.description}</p>{lesson.pdfUrl && <button type="button" onClick={() => window.open(lesson.pdfUrl, '_blank', 'noopener,noreferrer')} className={btn('secondary', 'md', 'mt-4')}><FileTextIcon className="h-4 w-4" /> View lecture notes</button>}<div className="mt-5 flex justify-between border-t border-line pt-5"><button disabled={!previous} onClick={() => previous && navigate(`/learn/${course._id}/${previous._id}`)} className={btn('secondary', 'md')}><ChevronLeftIcon className="h-4 w-4" /> Previous</button><button disabled={!next} onClick={() => next && navigate(`/learn/${course._id}/${next._id}`)} className={btn('primary', 'md')}>Next <ChevronRightIcon className="h-4 w-4" /></button></div></div></div><aside className="hidden overflow-hidden rounded-2xl border border-line bg-white lg:block lg:h-[calc(100vh-6.5rem)] lg:sticky lg:top-[4.75rem]">{playlist}</aside></div>
    {playlistOpen && <div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-slate-900/40" onClick={() => setPlaylistOpen(false)} /><div className="absolute inset-y-0 right-0 w-[86%] max-w-sm bg-white shadow-lift">{playlist}</div></div>}
  </div>;
}
