import { getCourseLectureGroups } from '../services/courses/courseSubjects';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { CheckCircle2Icon, CheckIcon, ChevronLeftIcon, ChevronRightIcon, FileTextIcon, ListIcon, LockIcon, PlayIcon } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { Badge, btn } from '../components/ui/Primitives';
import { Logo } from '../components/layout/Logo';
import { useViewer } from '../contexts/ViewerContext';
import { fetchPublicCourse } from '../services/courses/courses.slice';
import type { AppDispatch, RootState } from '../store';

export function VideoViewer() {
  const { courseId = '', lessonId = '' } = useParams(); const dispatch = useDispatch<AppDispatch>(); const navigate = useNavigate(); const { openPdf } = useViewer();
  const { publicCurrent, loading } = useSelector((state: RootState) => state.courses); const [completed, setCompleted] = useState<string[]>([]); const playlistRef = useRef<HTMLElement>(null);
  useEffect(() => { if (courseId) dispatch(fetchPublicCourse(courseId)); }, [courseId, dispatch]);
  const course = publicCurrent?._id === courseId ? publicCurrent : null;
  const playable = useMemo(() => course ? getCourseLectureGroups(course.subjects, course.lectures).flatMap((group) => group.lectures).filter((lecture) => Boolean(lecture.url)) : [], [course]);
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-canvas"><p className="text-sm text-ink-muted">Loading lecture...</p></div>;
  if (!course) return <div className="flex min-h-screen items-center justify-center bg-canvas"><Link to="/courses" className={btn('primary', 'md')}>Back to courses</Link></div>;
  const lesson = course.lectures.find((lecture) => lecture._id === lessonId); if (!lesson || !lesson.url) return <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-canvas"><LockIcon className="h-8 w-8 text-ink-muted" /><p className="text-sm text-ink-soft">This lecture is not available with your current access.</p><Link to={`/courses/${course._id}`} className={btn('primary', 'md')}>Back to course</Link></div>;
  const index = playable.findIndex((item) => item._id === lesson._id); const previous = playable[index - 1]; const next = playable[index + 1]; const done = completed.includes(lesson._id);
  const playlist = <div className="flex h-full min-h-0 flex-col">
    <div className="border-b border-line px-5 py-4"><h2 className="font-semibold text-ink">Course content</h2><p className="mt-1 text-xs text-ink-muted">{course.subjects?.length ? course.subjects.length + ' subjects · ' : ''}{course.lectures.length} lectures · Select a lecture to start learning</p></div>
    <div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-3 sm:p-4">
      {getCourseLectureGroups(course.subjects, course.lectures).map((group) => {
        const lectureRows = <div className="space-y-1 p-2">{group.lectures.map((item, itemIndex) => item.url ? <Link key={item._id} to={`/learn/${course._id}/${item._id}`} aria-current={item._id === lesson._id ? 'page' : undefined} className={`flex items-start gap-3 rounded-xl border px-3 py-3 transition-colors ${item._id === lesson._id ? 'border-brand-200 bg-brand-50' : 'border-transparent hover:bg-canvas'}`}>
          <span className="mt-0.5 shrink-0">{completed.includes(item._id) ? <CheckCircle2Icon className="h-4 w-4 text-emerald-500" /> : <PlayIcon className="h-4 w-4 text-brand-600" />}</span>
          <span className="min-w-0 flex-1"><span className="block text-sm font-medium leading-5 text-ink">{itemIndex + 1}. {item.title}</span><span className="mt-1 block text-xs text-ink-muted">{item.duration || (item.videoSource === 'youtube' ? 'YouTube lecture' : 'Video lecture')}{item.pdfUrl ? ' · PDF notes' : ''}</span></span>
          {item._id === lesson._id && <span className="shrink-0 rounded-full bg-brand-100 px-2 py-1 text-[10px] font-semibold text-brand-700">Playing</span>}
        </Link> : <div key={item._id} className="flex items-start gap-3 rounded-xl px-3 py-3 text-ink-muted"><LockIcon className="mt-0.5 h-4 w-4 shrink-0" /><div className="min-w-0"><p className="text-sm leading-5">{itemIndex + 1}. {item.title}</p><p className="mt-1 text-xs">Purchase required</p></div></div>)}</div>;
        return group.name ? <details key={group.name} open={group.lectures.some((item) => item._id === lesson._id) || undefined} className="overflow-hidden rounded-xl border border-line"><summary className="cursor-pointer bg-canvas px-4 py-3 text-sm font-semibold text-ink marker:text-brand-600">{group.name}<span className="ml-2 text-xs font-normal text-ink-muted">{group.lectures.length} lectures</span></summary>{lectureRows}{!group.lectures.length && <p className="px-4 py-4 text-xs text-ink-muted">No lectures added yet.</p>}</details> : <div key={group.name}>{lectureRows}</div>;
      })}
    </div>
  </div>;
  return <div className="flex min-h-screen w-full flex-col bg-canvas"><header className="sticky top-0 z-40 flex h-16 items-center gap-3 border-b border-line bg-white px-4 sm:px-6"><Logo /><div className="ml-2 hidden min-w-0 border-l border-line pl-4 sm:block"><p className="truncate text-[13px] font-semibold text-ink">{course.title}</p><p className="truncate text-xs text-ink-muted">{lesson.title}</p></div><div className="ml-auto flex gap-2"><button onClick={() => playlistRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })} className={btn('secondary', 'sm', 'lg:hidden')}><ListIcon className="h-4 w-4" /> Lectures</button><Link to={`/courses/${course._id}`} className={btn('secondary', 'sm')}>Course page</Link></div></header>
    <div className="mx-auto grid w-full max-w-none flex-1 items-start gap-5 px-4 py-5 sm:px-6 lg:grid-cols-2 lg:px-6"><aside ref={playlistRef} aria-label="Subject-wise course lectures" className="h-[min(70dvh,600px)] min-w-0 scroll-mt-20 overflow-hidden rounded-2xl border border-line bg-white lg:sticky lg:top-[4.75rem] lg:h-[calc(100dvh-6.5rem)]">{playlist}</aside><div className="min-w-0 lg:sticky lg:top-[4.75rem]"><div className="overflow-hidden rounded-2xl bg-black">{lesson.videoSource === 'youtube' ? <iframe key={lesson.url} src={lesson.url} title={lesson.title} className="aspect-video w-full border-0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen /> : <video key={lesson.url} src={lesson.url} controls controlsList="nodownload" disablePictureInPicture onContextMenu={(event) => event.preventDefault()} className="aspect-video w-full" />}</div><div className="mt-5 rounded-2xl border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone="brand">Lecture {course.lectures.findIndex((item) => item._id === lesson._id) + 1}</Badge><h1 className="mt-2.5 text-xl font-bold text-ink">{lesson.title}</h1></div><div className="flex flex-wrap gap-2"><button onClick={() => setCompleted((items) => items.includes(lesson._id) ? items : [...items, lesson._id])} className={btn(done ? 'secondary' : 'primary', 'md')}>{done ? <><CheckIcon className="h-4 w-4" /> Completed</> : 'Mark as completed'}</button>{lesson.pdfUrl && <button type="button" onClick={() => openPdf({ title: lesson.title, subtitle: course.title, module: 'course', url: lesson.pdfUrl, pages: [] })} className={btn('secondary', 'md')}><FileTextIcon className="h-4 w-4" /> View lecture notes</button>}</div></div><p className="mt-3 text-sm leading-6 text-ink-soft">{lesson.description}</p><div className="mt-5 flex justify-between border-t border-line pt-5"><button disabled={!previous} onClick={() => previous && navigate(`/learn/${course._id}/${previous._id}`)} className={btn('secondary', 'md')}><ChevronLeftIcon className="h-4 w-4" /> Previous</button><button disabled={!next} onClick={() => next && navigate(`/learn/${course._id}/${next._id}`)} className={btn('primary', 'md')}>Next <ChevronRightIcon className="h-4 w-4" /></button></div></div></div></div>

  </div>;
}
