const router = require('express').Router();
const controller = require('./testSeries.controller');
const { requireAuth, requireRole, optionalAuth } = require('../auth/auth.middleware');
router.get('/', optionalAuth, controller.list);
router.get('/admin', requireAuth, requireRole('admin'), controller.adminList);
router.get('/admin/:id', requireAuth, requireRole('admin'), controller.adminDetail);
router.get('/:id', optionalAuth, controller.detail);
router.post('/:id/checkout', requireAuth, requireRole('student'), controller.checkout);
router.post('/:id/checkout/verify', requireAuth, requireRole('student'), controller.verifyPayment);
router.post('/', requireAuth, requireRole('admin'), controller.create);
router.patch('/:id', requireAuth, requireRole('admin'), controller.update);
router.delete('/:id', requireAuth, requireRole('admin'), controller.remove);
router.post('/:id/tests', requireAuth, requireRole('admin'), controller.addTest);
router.post('/:id/purchase', requireAuth, requireRole('student'), controller.purchase);
router.post('/:seriesId/tests/:testId/attempts', requireAuth, requireRole('student'), controller.attempt);
router.get('/:id/results', requireAuth, requireRole('student'), controller.results);
module.exports = router;
