import { useState } from 'react';
import type { ReactNode } from 'react';
import { CheckCircleIcon, XCircleIcon } from 'lucide-react';
import { Panel } from '../ui/PageShell';
import { Badge, Button, Select } from '../ui/Primitives';
import { RichText, explanationTextClass, optionTextClass, questionTextClass } from '../ui/RichText';
import type { ReviewResult } from '../../services/question-review/questionReview.api';

export type AnswerStatus = 'correct' | 'incorrect' | 'skipped';
export function answerStatus(question: ReviewResult['questions'][number], answers: ReviewResult['answers']): AnswerStatus {
  const answer = answers[question._id];
  return answer === null || answer === undefined ? 'skipped' : answer === question.correctAnswer ? 'correct' : 'incorrect';
}
const colours = { correct: 'border-emerald-600 bg-emerald-600 text-white', incorrect: 'border-red-500 bg-red-500 text-white', skipped: 'border-line bg-white text-ink-soft' };
const labels = { correct: 'Correct', incorrect: 'Incorrect', skipped: 'Skipped' };

export function SolutionReview({ result, index, onJump, name, actions, navigation }: { result: ReviewResult; index: number; onJump: (index: number) => void; name: string; actions: ReactNode; navigation: ReactNode }) {
  const [filter, setFilter] = useState<AnswerStatus | 'all'>('all');
  const [practiceMode, setPracticeMode] = useState(false);
  const [practiceAnswers, setPracticeAnswers] = useState<Record<string, number>>({});
  const [revealed, setRevealed] = useState<Record<string, boolean>>({});
  const question = result.questions[index]; const answer = result.answers[question._id]; const status = answerStatus(question, result.answers);
  const practiceAnswer = practiceAnswers[question._id];
  const showAnswer = !practiceMode || practiceAnswer !== undefined || Boolean(revealed[question._id]);
  const counts = result.questions.reduce((counts, question) => { counts[answerStatus(question, result.answers)] += 1; return counts; }, { correct: 0, incorrect: 0, skipped: 0 });
  return <div className="grid items-start gap-4 pb-28 lg:grid-cols-[minmax(0,1fr)_300px]">
    <Panel padded={false} className="min-w-0 p-5 sm:p-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><p className="text-xs font-semibold text-brand-700">Question {index + 1} of {result.questions.length}</p>{!practiceMode && <Badge tone={status === 'correct' ? 'green' : status === 'incorrect' ? 'red' : 'slate'}>{result.preview ? 'Not attempted' : labels[status]}</Badge>}</div><div className="flex flex-wrap gap-2">{actions}</div></div>
      <RichText value={question.text} className={`mt-5 ${questionTextClass}`} />
      <div className="mt-6 space-y-3">{question.options.map((option, optionIndex) => {
        const correct = showAnswer && optionIndex === question.correctAnswer;
        const chosen = optionIndex === (practiceMode ? practiceAnswer : answer);
        const tone = correct ? 'border-emerald-300 bg-emerald-50' : chosen && showAnswer ? 'border-red-300 bg-red-50' : chosen ? 'border-brand-300 bg-brand-50' : 'border-line';
        const content = <><div className="flex items-start gap-2">{correct ? <CheckCircleIcon className="mt-1 h-5 w-5 shrink-0 text-emerald-600" /> : chosen && showAnswer ? <XCircleIcon className="mt-1 h-5 w-5 shrink-0 text-red-600" /> : null}<span className={optionTextClass}>{String.fromCharCode(65 + optionIndex)}.</span><RichText value={option} className={`min-w-0 flex-1 ${optionTextClass}`} /></div>{showAnswer && (chosen || correct) && <p className={`mt-2 text-sm font-semibold ${correct ? 'text-emerald-700' : 'text-red-600'}`}>{chosen && correct ? 'Your answer · Correct answer' : correct ? 'Correct answer' : 'Your answer · Incorrect'}</p>}</>;
        return practiceMode ? <button key={optionIndex} type="button" disabled={practiceAnswer !== undefined} onClick={() => setPracticeAnswers(current => ({ ...current, [question._id]: optionIndex }))} className={`w-full rounded-xl border p-4 text-left disabled:cursor-default ${tone}`}>{content}</button> : <div key={optionIndex} className={`rounded-xl border p-4 ${tone}`}>{content}</div>;
      })}</div>
      {practiceMode && <div className="mt-5 flex flex-wrap items-center gap-3 rounded-xl bg-amber-50 p-3 text-sm text-ink-soft"><span>Re-attempt mode: ON</span>{practiceAnswer === undefined && <span>Choose an answer to check yourself.</span>}{practiceAnswer !== undefined && <button type="button" className="font-semibold text-brand-700" onClick={() => { setPracticeAnswers(current => { const next = { ...current }; delete next[question._id]; return next; }); setRevealed(current => { const next = { ...current }; delete next[question._id]; return next; }); }}>Try again</button>}<button type="button" className="font-semibold text-brand-700" onClick={() => setRevealed(current => ({ ...current, [question._id]: true }))}>View Solution</button></div>}
      {!practiceMode && <div className="mt-5 flex flex-wrap gap-3 rounded-xl bg-canvas p-3 text-xs text-ink-soft"><span>Your answer: <strong>{answer === null || answer === undefined ? 'Not attempted' : String.fromCharCode(65 + answer)}</strong></span><span>Correct answer: <strong>{String.fromCharCode(65 + question.correctAnswer)}</strong></span></div>}
      {(!practiceMode || revealed[question._id]) && <div className="mt-5 rounded-xl bg-brand-50 p-4 text-ink-soft"><h2 className="font-semibold text-brand-700">Solution</h2><RichText value={question.explanation || `The correct answer is option ${String.fromCharCode(65 + question.correctAnswer)}.`} className={`mt-2 ${explanationTextClass}`} /></div>}
      <footer aria-label="Solution navigation" className="fixed inset-x-0 bottom-0 z-30 border-t border-line bg-white px-3 pt-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] shadow-soft sm:px-6 sm:pt-3"><div className="flex min-w-0 items-center justify-between gap-2 sm:gap-3"><Button size="sm" variant="secondary" className="shrink-0" disabled={index === 0} onClick={() => { setFilter('all'); onJump(index - 1); }}>Previous</Button><div className="flex min-w-0 flex-1 items-center justify-center gap-3"><label className="flex shrink-0 cursor-pointer items-center gap-1.5 whitespace-nowrap text-xs text-ink-soft sm:gap-2 sm:text-sm"><span className="sm:hidden">Re-attempt</span><span className="hidden sm:inline">Re-attempt questions</span><input type="checkbox" role="switch" aria-label="Re-attempt questions" checked={practiceMode} onChange={event => { setPracticeMode(event.target.checked); setFilter('all'); }} className="h-4 w-4 shrink-0 accent-brand-600" /></label><div className="hidden sm:block">{navigation}</div></div><Button size="sm" className="shrink-0" disabled={index === result.questions.length - 1} onClick={() => { setFilter('all'); onJump(index + 1); }}>Next</Button></div></footer>
    </Panel>
    <aside className="lg:sticky lg:top-20"><Panel><p className="font-semibold text-ink">{name}</p><h2 className="mt-1 text-sm text-ink-muted">{practiceMode ? 'Re-attempt practice' : result.preview ? 'Answer key' : 'Answer analysis'}</h2>{!practiceMode && !result.preview && <div className="mt-4 grid grid-cols-3 gap-2">{(['correct', 'incorrect', 'skipped'] as const).map((key) => <div key={key} className="rounded-lg bg-canvas p-2 text-center"><p className={`text-lg font-bold ${key === 'correct' ? 'text-emerald-600' : key === 'incorrect' ? 'text-red-600' : 'text-ink-muted'}`}>{counts[key]}</p><p className="text-[10px] text-ink-soft">{labels[key]}</p></div>)}</div>}<div className="mt-5 flex items-center justify-between gap-2"><h2 className="text-sm font-semibold text-ink">Questions</h2>{!practiceMode && !result.preview && <Select aria-label="Filter questions by answer status" className="!h-9 !w-auto !px-2 !text-xs" value={filter} onChange={(event) => { const next = event.target.value as AnswerStatus | 'all'; setFilter(next); if (next !== 'all' && status !== next) { const first = result.questions.findIndex((question) => answerStatus(question, result.answers) === next); if (first >= 0) onJump(first); } }}><option value="all">All</option><option value="correct">Correct</option><option value="incorrect">Incorrect</option><option value="skipped">Skipped</option></Select>}</div><div className="mt-4 grid grid-cols-5 gap-2">{result.questions.map((item, itemIndex) => { const state = answerStatus(item, result.answers); const practiceAnswerForItem = practiceAnswers[item._id]; const practiceState = practiceAnswerForItem === undefined ? 'skipped' : practiceAnswerForItem === item.correctAnswer ? 'correct' : 'incorrect'; if (!practiceMode && filter !== 'all' && filter !== state) return null; return <button key={item._id} type="button" aria-label={`Question ${itemIndex + 1}: ${practiceMode ? practiceAnswerForItem === undefined ? 'Not attempted' : labels[practiceState] : labels[state]}`} aria-current={itemIndex === index ? 'step' : undefined} onClick={() => onJump(itemIndex)} className={`h-10 rounded-lg border text-xs font-semibold ${colours[practiceMode ? practiceState : state]} ${itemIndex === index ? 'ring-2 ring-brand-400 ring-offset-2' : ''}`}>{itemIndex + 1}</button>; })}</div>{!practiceMode && filter !== 'all' && counts[filter] === 0 && <p className="mt-3 text-xs text-ink-muted">No {filter} questions.</p>}<p className="mt-4 text-xs leading-5 text-ink-muted">{practiceMode ? 'Choose an option to check your answer. Green: correct · Red: incorrect · White: not attempted.' : result.preview ? 'Click a question number to read its answer and explanation.' : 'Green: correct · Red: incorrect · White: skipped. Click a question number to jump directly to it.'}</p></Panel></aside>
  </div>;
}
