import { useState } from 'react';
import type { ReactNode } from 'react';
import { CheckCircleIcon, XCircleIcon } from 'lucide-react';
import { Panel } from '../ui/PageShell';
import { Badge, Button, Select } from '../ui/Primitives';
import type { ReviewResult } from '../../services/question-review/questionReview.api';

export type AnswerStatus = 'correct' | 'incorrect' | 'skipped';
export function answerStatus(question: ReviewResult['questions'][number], answers: ReviewResult['answers']): AnswerStatus {
  const answer = answers[question._id];
  return answer === null || answer === undefined ? 'skipped' : answer === question.correctAnswer ? 'correct' : 'incorrect';
}
const colours = { correct: 'border-emerald-600 bg-emerald-600 text-white', incorrect: 'border-red-500 bg-red-500 text-white', skipped: 'border-line bg-white text-ink-soft' };
const labels = { correct: 'Correct', incorrect: 'Incorrect', skipped: 'Skipped' };

export function SolutionReview({ result, index, onJump, name, actions, navigation }: { result: ReviewResult; index: number; onJump: (index: number) => void; name: string; actions: ReactNode; navigation: ReactNode }) {
  const [filter, setFilter] = useState<AnswerStatus | 'all'>('all');
  const question = result.questions[index]; const answer = result.answers[question._id]; const status = answerStatus(question, result.answers);
  const counts = result.questions.reduce((counts, question) => { counts[answerStatus(question, result.answers)] += 1; return counts; }, { correct: 0, incorrect: 0, skipped: 0 });
  return <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_300px]">
    <Panel><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><p className="text-xs font-semibold text-brand-700">Question {index + 1} of {result.questions.length}</p><Badge tone={status === 'correct' ? 'green' : status === 'incorrect' ? 'red' : 'slate'}>{labels[status]}</Badge></div><div className="flex flex-wrap gap-2">{actions}</div></div>
      <h1 className="whitespace-pre-wrap text-lg font-semibold leading-7 text-ink">{question.text}</h1>
      <div className="mt-5 space-y-3">{question.options.map((option, optionIndex) => { const correct = optionIndex === question.correctAnswer; const chosen = optionIndex === answer; return <div key={optionIndex} className={`rounded-xl border p-4 text-sm ${correct ? 'border-emerald-300 bg-emerald-50' : chosen ? 'border-red-300 bg-red-50' : 'border-line'}`}><div className="flex items-start gap-2">{correct ? <CheckCircleIcon className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" /> : chosen ? <XCircleIcon className="mt-0.5 h-4 w-4 shrink-0 text-red-600" /> : null}<p className="whitespace-pre-wrap">{String.fromCharCode(65 + optionIndex)}. {option}</p></div>{(chosen || correct) && <p className={`mt-2 text-xs font-semibold ${correct ? 'text-emerald-700' : 'text-red-600'}`}>{chosen && correct ? 'Your answer · Correct answer' : correct ? 'Correct answer' : 'Your answer · Incorrect'}</p>}</div>; })}</div>
      <div className="mt-5 flex flex-wrap gap-3 rounded-xl bg-canvas p-3 text-xs text-ink-soft"><span>Your answer: <strong>{answer === null || answer === undefined ? 'Not attempted' : String.fromCharCode(65 + answer)}</strong></span><span>Correct answer: <strong>{String.fromCharCode(65 + question.correctAnswer)}</strong></span></div>
      <div className="mt-5 rounded-xl bg-brand-50 p-4 text-sm text-ink-soft"><h2 className="font-semibold text-brand-700">Solution</h2><p className="mt-2 whitespace-pre-wrap">{question.explanation || `The correct answer is option ${String.fromCharCode(65 + question.correctAnswer)}.`}</p></div>
      <div className="mt-6 flex items-center justify-between gap-2"><Button variant="secondary" size="sm" disabled={index === 0} onClick={() => { setFilter('all'); onJump(index - 1); }}>Previous</Button>{navigation}<Button size="sm" disabled={index === result.questions.length - 1} onClick={() => { setFilter('all'); onJump(index + 1); }}>Next</Button></div>
    </Panel>
    <aside className="lg:sticky lg:top-20"><Panel><p className="font-semibold text-ink">{name}</p><h2 className="mt-1 text-sm text-ink-muted">Answer analysis</h2><div className="mt-4 grid grid-cols-3 gap-2">{(['correct', 'incorrect', 'skipped'] as const).map((key) => <div key={key} className="rounded-lg bg-canvas p-2 text-center"><p className={`text-lg font-bold ${key === 'correct' ? 'text-emerald-600' : key === 'incorrect' ? 'text-red-600' : 'text-ink-muted'}`}>{counts[key]}</p><p className="text-[10px] text-ink-soft">{labels[key]}</p></div>)}</div><div className="mt-5 flex items-center justify-between gap-2"><h2 className="text-sm font-semibold text-ink">Questions</h2><Select aria-label="Filter questions by answer status" className="!h-9 !w-auto !px-2 !text-xs" value={filter} onChange={(event) => { const next = event.target.value as AnswerStatus | 'all'; setFilter(next); if (next !== 'all' && status !== next) { const first = result.questions.findIndex((question) => answerStatus(question, result.answers) === next); if (first >= 0) onJump(first); } }}><option value="all">All</option><option value="correct">Correct</option><option value="incorrect">Incorrect</option><option value="skipped">Skipped</option></Select></div><div className="mt-4 grid grid-cols-5 gap-2">{result.questions.map((item, itemIndex) => { const state = answerStatus(item, result.answers); if (filter !== 'all' && filter !== state) return null; return <button key={item._id} type="button" aria-label={`Question ${itemIndex + 1}: ${labels[state]}`} aria-current={itemIndex === index ? 'step' : undefined} onClick={() => onJump(itemIndex)} className={`h-10 rounded-lg border text-xs font-semibold ${colours[state]} ${itemIndex === index ? 'ring-2 ring-brand-400 ring-offset-2' : ''}`}>{itemIndex + 1}</button>; })}</div>{filter !== 'all' && counts[filter] === 0 && <p className="mt-3 text-xs text-ink-muted">No {filter} questions.</p>}<p className="mt-4 text-xs leading-5 text-ink-muted">Green: correct · Red: incorrect · White: skipped. Click a question number to jump directly to it.</p></Panel></aside>
  </div>;
}
