import { useEffect, useRef, useState } from 'react';
import { UserIcon } from 'lucide-react';
import { Button } from '../ui/Primitives';

export interface AttemptQuestion { _id: string; text: string; options: string[]; marks?: number; negativeMarks?: number }
export function CandidatePhoto({ src, name }: { src?: string; name: string }) {
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [src]);
  return <div className="flex flex-col items-center gap-3"><div className="flex h-36 w-32 items-center justify-center overflow-hidden rounded-xl border border-line bg-slate-50">{src && !failed ? <img src={src} onError={() => setFailed(true)} alt={`${name}'s test photo`} className="h-full w-full object-cover" /> : <UserIcon aria-label="Default user photo" className="h-24 w-24 text-slate-400" />}</div><p className="text-center text-sm font-semibold text-ink">{name}</p></div>;
}
export const questionStatusClasses = { unanswered: 'bg-blue-600 text-white', answered: 'bg-emerald-600 text-white', review: 'bg-red-500 text-white', answeredReview: 'bg-yellow-300 text-slate-900' };

export function TestInstructions({ title, questions, duration = 0, languages = 'English', name, onStart, onExit }: { title: string; questions: AttemptQuestion[]; duration?: number; languages?: string; name: string; onStart: (photo: File | null) => void; onExit: () => void }) {
  const [agreed, setAgreed] = useState(false);
  const photoInput = useRef<HTMLInputElement>(null);
  const [photo, setPhoto] = useState<File | null>(null);
  const [preview, setPreview] = useState('');
  const [photoError, setPhotoError] = useState('');
  const [starting, setStarting] = useState(false);
  useEffect(() => { if (!photo) { setPreview(''); return; } const url = URL.createObjectURL(photo); setPreview(url); return () => URL.revokeObjectURL(url); }, [photo]);
  const totalMarks = questions.reduce((sum, question) => sum + (question.marks ?? 1), 0);
  const uniform = (key: 'marks' | 'negativeMarks', fallback: number) => { const values = [...new Set(questions.map((question) => question[key] ?? fallback))]; return values.length === 1 ? values[0] : 'Varies by question'; };
  const legend = [
    [<span className="text-2xl text-brand-600">○</span>, 'Option not chosen.'],
    [<span className="text-2xl text-brand-600">◉</span>, 'Option chosen as your answer. Click it again to remove your selection, or choose another option.'],
    [<span className={`rounded px-3 py-1 ${questionStatusClasses.unanswered}`}>1</span>, 'A question number shown in blue indicates that you have not yet answered the question.'],
    [<span className={`rounded px-3 py-1 ${questionStatusClasses.answered}`}>1</span>, 'A question number shown in green indicates that you have answered the question.'],
    [<span className={`rounded px-3 py-1 ${questionStatusClasses.review}`}>3 ▲</span>, 'You have not yet answered the question but have marked it to come back for review later, if time permits.'],
    [<span className={`rounded px-3 py-1 ${questionStatusClasses.answeredReview}`}>3 ▲</span>, 'You have answered the question but have marked it for review later, if time permits.'],
    [<span className="rounded bg-brand-600 px-2 py-1 text-white">Save & Next</span>, 'Saves your answer and takes you to the next question.'],
    [<span className="rounded bg-brand-600 px-2 py-1 text-white">Previous</span>, 'Takes you to the previous question.'],
    [<span className="rounded bg-slate-100 px-2 py-1">Mark for Review</span>, 'Saves your answer, marks the question for review and goes to the next question. An answered question marked for review is evaluated even if you do not review it.'],
    [<span className="rounded bg-slate-100 px-2 py-1">Unmark</span>, 'Removes the review mark from the question.'],
  ];
  return <div className="min-h-screen bg-canvas px-4 py-6 sm:px-6"><div className="mx-auto max-w-6xl space-y-5">
    <header className="rounded-2xl border border-brand-100 bg-brand-50 p-5 text-center"><h1 className="text-xl font-bold text-brand-700 sm:text-3xl">{title}</h1><p className="mt-2 text-sm font-semibold text-brand-700">Please read the following instructions carefully</p></header>
    <section className="rounded-2xl border border-line bg-white p-4 sm:p-6"><p className="font-semibold text-ink">Total Number of Questions: {questions.length}</p><p className="mt-1 font-semibold text-ink">Total Time Available: {duration ? `${duration} Mins` : 'No time limit'}</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] border-collapse text-center text-sm"><thead className="bg-brand-50 text-brand-700"><tr>{['Section #', 'Section Name', 'Total Number of Questions', 'Max Score', 'Marks for correct Answer', 'Negative Marking for Wrong Answer'].map((label) => <th key={label} className="border border-line p-3">{label}</th>)}</tr></thead><tbody><tr>{[1, 'Sectional', questions.length, totalMarks, uniform('marks', 1), uniform('negativeMarks', 0)].map((value, index) => <td key={index} className="border border-line p-3">{value}</td>)}</tr></tbody></table></div></section>
    <section><p className="mb-3 text-sm font-medium text-ink">The different symbols used in the next pages are shown below. Please go through them and understand their meaning before you start the test.</p><div className="grid gap-4 lg:grid-cols-[1fr_220px]"><div className="overflow-hidden rounded-2xl border border-line bg-white"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-center">Symbol</th><th className="p-3 text-left">Meaning</th></tr></thead><tbody>{legend.map(([symbol, meaning], index) => <tr key={index} className="border-t border-line"><td className="w-40 p-3 text-center text-xs font-semibold">{symbol}</td><td className="border-l border-line p-3 text-ink-soft">{meaning}</td></tr>)}</tbody></table></div><aside className="rounded-2xl border border-line bg-white p-4"><CandidatePhoto src={preview} name={name} /><p className="mt-3 text-center text-xs text-ink-muted">Your photo appears here</p><label className="mt-4 block text-xs font-medium text-ink">Upload photo (optional)<input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block w-full text-xs" onChange={(event) => { const file = event.target.files?.[0] || null; if (file && (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024)) { setPhotoError('Choose a JPG, PNG or WebP image up to 5 MB.'); event.target.value = ''; return; } setPhotoError(''); setPhoto(file); }} /></label><p className="mt-2 text-xs text-ink-muted">Up to 5 MB. Used only for this attempt.</p>{photo && <Button type="button" variant="ghost" size="sm" className="mt-2" onClick={() => { setPhoto(null); setPhotoError(''); if (photoInput.current) photoInput.current.value = ''; }}>Remove photo</Button>}{photoError && <p role="alert" className="mt-2 text-xs text-red-600">{photoError}</p>}</aside></div></section>
    <section className="rounded-2xl border border-line bg-white p-4 text-sm leading-6 text-ink-soft sm:p-6">
      <h2 className="text-base font-bold text-brand-700 underline">General Instructions:</h2><ol className="mt-2 list-decimal space-y-1 pl-6"><li>{duration ? `A total duration of ${duration} minutes will be given to attempt all the questions.` : 'This test has no time limit.'}</li><li>{duration ? 'The countdown timer at the top right corner of the screen displays the remaining time. When the clock runs out, the test ends and your saved answers are submitted automatically; you do not need to end or submit the exam.' : 'Click Submit Test when you have finished answering the questions.'}</li><li>The question palette at the right of the screen helps you navigate through the questions.</li></ol>
      <h2 className="mt-4 text-base font-bold text-brand-700 underline">Navigating to a Question</h2><ol start={4} className="mt-2 list-decimal space-y-1 pl-6"><li>To select a question to answer, you can do one of the following:<ol className="list-[lower-alpha] pl-6"><li>Click the question number on the question palette to go directly to that question. This does NOT save your answer to the current question.</li><li>Click <strong>Save & Next</strong> to save your answer and go to the next question in sequence.</li><li>Click <strong>Mark for Review & Next</strong> to save your answer, mark it for review and go to the next question in sequence.</li></ol></li><li>You can view the entire paper by clicking the <strong>Question Paper</strong> button.</li></ol>
      <h2 className="mt-4 text-base font-bold text-brand-700 underline">Answering a Question</h2><ol start={6} className="mt-2 list-decimal space-y-1 pl-6"><li>For a multiple-choice question:<ol className="list-[lower-alpha] pl-6"><li>To select your answer, click one of the option buttons.</li><li>To change your answer, click another desired option button.</li><li>To save your answer, you MUST click <strong>Save & Next</strong>.</li><li>To mark the question for review, click <strong>Mark for Review & Next</strong>. If an answer is selected for a question marked for review, that answer will be considered in the evaluation.</li></ol></li><li>To change an answer, first select the question, click the new answer option, then click <strong>Save & Next</strong>.</li><li>Only questions that are saved, or marked for review after answering, will be considered for evaluation.</li></ol>
      <div className="mt-5 border-t border-line pt-4"><label className="flex flex-wrap items-center justify-center gap-3 font-medium">Choose Language:<select className="rounded-lg border border-line bg-white px-3 py-2" defaultValue={languages}><option value={languages}>{languages}</option></select></label><label className="mt-5 flex cursor-pointer items-start gap-3"><input type="checkbox" checked={agreed} onChange={(event) => setAgreed(event.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-blue-600" /><span><strong className="text-brand-700">Declaration:</strong> I have understood and agree to all the instructions and do hereby declare that I will not indulge in any unfair practice during the test.</span></label></div>
    </section><div className="flex flex-wrap justify-center gap-3 pb-4"><Button variant="secondary" onClick={onExit}>Back</Button><Button size="lg" disabled={!agreed || !questions.length || starting} onClick={() => { if (!agreed) return; setStarting(true); onStart(photo); }}>I am ready to begin</Button></div>
  </div></div>;
}
