import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { PageShell, Panel } from '../../components/ui/PageShell';
import { Button, Field, Input, Select, Textarea, btn } from '../../components/ui/Primitives';
import { createNotice, fetchAdminNotice, updateNotice } from '../../services/notices/notices.slice';
import type { NoticePayload } from '../../services/notices/notices.api';
import type { AppDispatch, RootState } from '../../store';
const blank: NoticePayload = { title: '', description: '', type: 'vacancy', organization: '', location: '', eligibility: '', lastDate: null, applyUrl: '', status: 'draft' };
export function AdminNoticeForm() {
  const { noticeId } = useParams(); const editing = Boolean(noticeId); const dispatch = useDispatch<AppDispatch>(); const navigate = useNavigate(); const { current, loading, saving, error } = useSelector((state: RootState) => state.notices); const [draft, setDraft] = useState<NoticePayload>(blank);
  useEffect(() => { if (noticeId) dispatch(fetchAdminNotice(noticeId)); }, [noticeId, dispatch]);
  useEffect(() => { if (noticeId && current?._id === noticeId) { const { _id, createdAt, ...values } = current; setDraft({ ...values, lastDate: values.lastDate ? values.lastDate.slice(0, 10) : null }); } }, [noticeId, current]);
  const set = (key: keyof NoticePayload, value: string | null) => setDraft((item) => ({ ...item, [key]: value } as NoticePayload));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (noticeId) await dispatch(updateNotice({ id: noticeId, payload: draft })).unwrap(); else await dispatch(createNotice(draft)).unwrap(); navigate('/admin/notices'); };
  if (editing && loading) return <PageShell title="Edit Notice" subtitle="Loading notice..." width="max-w-4xl"><Panel><p className="text-sm text-ink-muted">Loading details...</p></Panel></PageShell>;
  return <PageShell title={editing ? 'Edit Notice' : 'Create Notice'} subtitle="Publish a vacancy, job post or general notice." width="max-w-4xl"><form onSubmit={(event) => { submit(event).catch(() => undefined); }} className="space-y-5"><Panel><div className="grid gap-4 sm:grid-cols-2"><Field label="Title" className="sm:col-span-2"><Input required value={draft.title} onChange={(e) => set('title', e.target.value)} /></Field><Field label="Notice type"><Select value={draft.type} onChange={(e) => set('type', e.target.value)}><option value="vacancy">Vacancy</option><option value="job">Job Post</option><option value="general">General Notice</option></Select></Field><Field label="Organization"><Input value={draft.organization} onChange={(e) => set('organization', e.target.value)} /></Field><Field label="Location"><Input value={draft.location} onChange={(e) => set('location', e.target.value)} /></Field><Field label="Last date"><Input type="date" value={draft.lastDate || ''} onChange={(e) => set('lastDate', e.target.value || null)} /></Field><Field label="Eligibility" className="sm:col-span-2"><Input value={draft.eligibility} onChange={(e) => set('eligibility', e.target.value)} placeholder="Qualification, age or experience requirements" /></Field><Field label="Description" className="sm:col-span-2"><Textarea required rows={5} value={draft.description} onChange={(e) => set('description', e.target.value)} /></Field><Field label="Details / apply URL" className="sm:col-span-2"><Input type="url" value={draft.applyUrl} onChange={(e) => set('applyUrl', e.target.value)} placeholder="https://..." /></Field><Field label="Status"><Select value={draft.status} onChange={(e) => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="unpublished">Unpublished</option></Select></Field></div></Panel>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Link to="/admin/notices" className={btn('secondary', 'md')}>Cancel</Link><Button type="submit" disabled={saving}>{saving ? 'Saving…' : editing ? 'Update notice' : 'Publish notice'}</Button></div></form></PageShell>;
}
