import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { CheckIcon, PlusIcon, Trash2Icon } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { exams } from '../../data/content';
import { PageShell, Panel } from '../../components/ui/PageShell';
import { Button, Field, Input, Select, Textarea, btn } from '../../components/ui/Primitives';
import { RichTextEditor } from '../../components/ui/RichText';
import { createCurrentAffairs, fetchAdminCurrentAffairsEntry, updateCurrentAffairs } from '../../services/current-affairs/currentAffairs.slice';
import type { CurrentAffairsQuestion, CurrentAffairsStatus } from '../../services/current-affairs/currentAffairs.api';
import type { AppDispatch, RootState } from '../../store';

type Question = CurrentAffairsQuestion & { key: string };
type Draft = { date: string; title: string; exam: string; highlights: string; status: CurrentAffairsStatus; file: File | null };
let sequence = 0;
const blankQuestion = (): Question => ({ key: `question-${sequence++}`, text: '', options: ['', '', '', ''], correctAnswer: 0, explanation: '' });
const today = new Date().toISOString().slice(0, 10);

export function AdminCurrentAffairsForm() {
  const { entryId } = useParams(); const editing = Boolean(entryId); const dispatch = useDispatch<AppDispatch>(); const navigate = useNavigate();
  const { current, loading, saving, error } = useSelector((state: RootState) => state.currentAffairs);
  const [draft, setDraft] = useState<Draft>({ date: today, title: '', exam: 'All Exams', highlights: '', status: 'draft', file: null }); const [questions, setQuestions] = useState<Question[]>([blankQuestion()]);
  useEffect(() => { if (entryId) dispatch(fetchAdminCurrentAffairsEntry(entryId)); }, [entryId, dispatch]);
  useEffect(() => { if (entryId && current?._id === entryId) { setDraft({ date: current.date.slice(0, 10), title: current.title, exam: current.exam, highlights: current.highlights.join('\n'), status: current.status, file: null }); setQuestions(current.questions.length ? current.questions.map((question) => ({ ...question, key: question._id || `question-${sequence++}` })) : [blankQuestion()]); } }, [entryId, current]);
  const set = (key: keyof Draft, value: string | File | null) => setDraft((item) => ({ ...item, [key]: value } as Draft));
  const updateQuestion = (key: string, patch: Partial<Question>) => setQuestions((items) => items.map((item) => item.key === key ? { ...item, ...patch } : item));
  const questionPayload = () => questions.map(({ key: _key, _id: _id, ...question }) => question);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const payload = { date: draft.date, title: draft.title, exam: draft.exam, highlights: draft.highlights.split('\n').map((item) => item.trim()).filter(Boolean), questions: questionPayload(), status: draft.status }; if (entryId) await dispatch(updateCurrentAffairs({ id: entryId, payload })).unwrap(); else { if (!draft.file) return; await dispatch(createCurrentAffairs({ ...payload, file: draft.file })).unwrap(); } navigate('/admin/current-affairs'); };

  if (editing && loading) return <PageShell title="Edit Current Affairs" subtitle="Loading entry..." width="max-w-5xl"><Panel><p className="text-sm text-ink-muted">Loading details...</p></Panel></PageShell>;
  return <PageShell title={editing ? 'Edit Current Affairs' : 'Add Daily Current Affairs'} subtitle="Manage the daily PDF capsule and its MCQ test." width="max-w-5xl"><form onSubmit={(event) => { submit(event).catch(() => undefined); }} className="space-y-5"><Panel><h2 className="text-base font-semibold text-ink">Daily current affairs</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">
    <Field label="Date"><Input required type="date" value={draft.date} onChange={(e) => set('date', e.target.value)} /></Field><Field label="Exam relevance"><Select value={draft.exam} onChange={(e) => set('exam', e.target.value)}><option>All Exams</option>{exams.map((exam) => <option key={exam}>{exam}</option>)}</Select></Field><Field label="Title" className="sm:col-span-2"><Input required value={draft.title} onChange={(e) => set('title', e.target.value)} placeholder="Daily Current Affairs" /></Field><Field label="Content / highlights" className="sm:col-span-2" hint="One highlight per line"><Textarea rows={4} value={draft.highlights} onChange={(e) => set('highlights', e.target.value)} /></Field>
    {!editing && <Field label="PDF upload" hint="PDF only · maximum 50 MB"><Input required type="file" accept="application/pdf" onChange={(e) => set('file', e.target.files?.[0] || null)} /></Field>}{editing && current && <Field label="Current PDF"><a href={current.pdfUrl} target="_blank" rel="noreferrer" className={btn('secondary', 'md')}>View current PDF</a></Field>}<Field label="Status"><Select value={draft.status} onChange={(e) => set('status', e.target.value)}><option value="published">Published</option><option value="draft">Draft</option><option value="unpublished">Unpublished</option></Select></Field>
  </div></Panel>
  <Panel><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-ink">Daily MCQ test</h2><p className="mt-1 text-[13px] text-ink-muted">{questions.length} of 10 questions added</p></div><Button type="button" variant="secondary" size="sm" disabled={questions.length >= 10} onClick={() => setQuestions((items) => [...items, blankQuestion()])}><PlusIcon className="h-4 w-4" /> Add question</Button></div><div className="mt-4 space-y-4">{questions.map((question, index) => <div key={question.key} className="rounded-xl border border-line p-4"><div className="flex items-center justify-between"><p className="text-[13px] font-semibold text-ink">Question {index + 1}</p><button type="button" disabled={questions.length === 1} onClick={() => setQuestions((items) => items.filter((item) => item.key !== question.key))} aria-label="Delete question" className="flex h-8 w-8 items-center justify-center rounded-lg text-ink-muted hover:bg-red-50 hover:text-red-600 disabled:opacity-40"><Trash2Icon className="h-4 w-4" /></button></div><div className="mt-3 grid gap-3"><Field label="Question" hint="Use x² for powers and x₂ for subscripts."><RichTextEditor value={question.text} onChange={(text) => updateQuestion(question.key, { text })} placeholder="Question text" ariaLabel={`Current affairs question ${index + 1}`} /></Field><div className="grid gap-2 sm:grid-cols-2">{question.options.map((option, optionIndex) => <Field key={optionIndex} label={`Option ${String.fromCharCode(65 + optionIndex)}`}><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><RichTextEditor value={option} onChange={(text) => updateQuestion(question.key, { options: question.options.map((item, i) => i === optionIndex ? text : item) })} placeholder={`Option ${String.fromCharCode(65 + optionIndex)}`} minHeight="52px" ariaLabel={`Option ${String.fromCharCode(65 + optionIndex)}`} /></div><button type="button" onClick={() => updateQuestion(question.key, { correctAnswer: optionIndex })} aria-label="Mark correct answer" className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${question.correctAnswer === optionIndex ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-line text-ink-muted'}`}><CheckIcon className="h-4 w-4" /></button></div></Field>)}</div><Field label="Explanation"><RichTextEditor value={question.explanation} onChange={(explanation) => updateQuestion(question.key, { explanation })} placeholder="Explanation" ariaLabel={`Explanation for current affairs question ${index + 1}`} /></Field></div></div>)}</div></Panel>
  {error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Link to="/admin/current-affairs" className={btn('secondary', 'md')}>Cancel</Link><Button type="submit" disabled={saving || (!editing && !draft.file)}>{saving ? 'Saving…' : editing ? 'Update entry' : 'Save entry'}</Button></div></form></PageShell>;
}
