import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CheckIcon, PlusIcon, Trash2Icon } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { exams } from '../../data/content';
import { PageShell, Panel } from '../../components/ui/PageShell';
import { Button, Field, Input, Select, Textarea, btn } from '../../components/ui/Primitives';
import { fetchPaperCatalog, createPreviousPaper, fetchAdminPreviousPaper, fetchAdminPreviousPapers, updatePreviousPaper } from '../../services/previous-papers/previousPapers.slice';
import type { PaperQuestion, PaperStatus } from '../../services/previous-papers/previousPapers.api';
import type { AppDispatch, RootState } from '../../store';
import { SubjectFolderChoice } from '../../components/admin/SubjectFolderChoice';
type Question = PaperQuestion & { key: string };
type Draft = { directory: string; title: string; exam: string; year: string; stage: string; shift: string; subject: string; duration: string; status: PaperStatus; file: File | null };
let sequence = 0; const blankQuestion = (): Question => ({ key: `paper-q-${sequence++}`, text: '', options: ['', '', '', ''], correctAnswer: 0, explanation: '', marks: 1, negativeMarks: 0.25 });
const blank: Draft = { directory: '', title: '', exam: 'SSC', year: String(new Date().getFullYear() - 1), stage: 'Tier 1', shift: 'Shift 1', subject: 'All Subjects', duration: '60', status: 'draft', file: null };
export function AdminPreviousPaperForm() {
  const { paperId } = useParams(); const [search] = useSearchParams(); const editing = Boolean(paperId); const dispatch = useDispatch<AppDispatch>(); const navigate = useNavigate(); const { catalog, current, items, loading, saving, error } = useSelector((state: RootState) => state.previousPapers);
  const [draft, setDraft] = useState<Draft>({ ...blank, directory: search.get('directory') || '' }); const [withTest, setWithTest] = useState(false); const [useSubject, setUseSubject] = useState(false); const [questions, setQuestions] = useState<Question[]>([blankQuestion()]);
  useEffect(() => { dispatch(fetchPaperCatalog()); }, [dispatch]);
  useEffect(() => { if (!paperId) dispatch(fetchAdminPreviousPapers()); }, [dispatch, paperId]);
  useEffect(() => { if (paperId) dispatch(fetchAdminPreviousPaper(paperId)); }, [paperId, dispatch]);
  useEffect(() => { if (paperId && current?._id === paperId) { setDraft({ directory: current.directory || current.exam, title: current.title, exam: current.exam, year: String(current.year), stage: current.stage, shift: current.shift, subject: current.subject, duration: String(current.duration || 60), status: current.status, file: null }); setUseSubject(current.subject !== 'All Subjects'); setWithTest(current.questions.length > 0); setQuestions(current.questions.length ? current.questions.map((question) => ({ ...question, key: question._id || `paper-q-${sequence++}` })) : [blankQuestion()]); } }, [paperId, current]);
  const set = (key: keyof Draft, value: string | File | null) => setDraft((item) => ({ ...item, [key]: value } as Draft)); const updateQuestion = (key: string, patch: Partial<Question>) => setQuestions((items) => items.map((item) => item.key === key ? { ...item, ...patch } : item));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const payload = { directory: draft.directory || draft.exam, title: draft.title, exam: draft.exam, year: Number(draft.year), stage: draft.stage, shift: draft.shift, subject: useSubject ? draft.subject.trim() : 'All Subjects', duration: withTest ? Number(draft.duration) : 0, questions: withTest ? questions.map(({ key: _key, ...question }) => question) : [], status: draft.status }; if (paperId) await dispatch(updatePreviousPaper({ id: paperId, payload: { ...payload, ...(draft.file ? { file: draft.file } : {}) } })).unwrap(); else { if (!draft.file && !payload.questions.length) return; await dispatch(createPreviousPaper({ ...payload, ...(draft.file ? { file: draft.file } : {}) })).unwrap(); } navigate(`/admin/previous-papers?directory=${encodeURIComponent(payload.directory)}`); };
  if (editing && loading) return <PageShell title="Edit Previous Paper" subtitle="Loading paper..." width="max-w-5xl"><Panel><p className="text-sm text-ink-muted">Loading details...</p></Panel></PageShell>;
  return <PageShell title={editing ? 'Edit Previous Paper' : 'Add Previous Paper'} subtitle="Add a PDF, an online MCQ test, or both." width="max-w-5xl"><form onSubmit={(event) => { submit(event).catch(() => undefined); }} className="space-y-5"><Panel><h2 className="text-base font-semibold text-ink">Paper details</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Title" className="sm:col-span-3"><Input required value={draft.title} onChange={(e) => set('title', e.target.value)} placeholder="SSC CGL 2025 Tier 1 Paper" /></Field><Field label="Paper collection"><Select required value={draft.directory} onChange={(e) => set('directory', e.target.value)}><option value="">Select collection</option>{catalog?.directories.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</Select></Field><Field label="Exam"><Select value={draft.exam} onChange={(e) => set('exam', e.target.value)}>{exams.map((exam) => <option key={exam}>{exam}</option>)}</Select></Field><Field label="Year"><Input required type="number" min="1950" value={draft.year} onChange={(e) => set('year', e.target.value)} /></Field><Field label="Tier / Stage"><Select value={draft.stage} onChange={(e) => set('stage', e.target.value)}>{['Tier 1', 'Tier 2', 'Prelims', 'Mains', 'CBT 1', 'CBT 2'].map((stage) => <option key={stage}>{stage}</option>)}</Select></Field><Field label="Shift"><Select value={draft.shift} onChange={(e) => set('shift', e.target.value)}>{['Shift 1', 'Shift 2', 'Shift 3'].map((shift) => <option key={shift}>{shift}</option>)}</Select></Field>{<Field label={editing ? "Replace or add PDF (optional)" : "PDF file (optional when adding an online test)"} hint="PDF only · maximum 50 MB"><Input type="file" accept="application/pdf" onChange={(e) => set('file', e.target.files?.[0] || null)} /></Field>}{editing && current?.pdfUrl && <Field label="Current PDF"><a href={current.pdfUrl} target="_blank" rel="noreferrer" className={btn('secondary', 'md')}>View current PDF</a></Field>}<Field label="Status"><Select value={draft.status} onChange={(e) => set('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="unpublished">Unpublished</option></Select></Field></div></Panel>
    <SubjectFolderChoice content="papers" enabled={useSubject} onToggle={setUseSubject} value={draft.subject} onChange={(subject) => set('subject', subject)} generalLabel="All Subjects" suggestions={[...new Set([...items.filter((paper) => (paper.directory || paper.exam) === draft.directory).map((paper) => paper.subject), 'Quantitative', 'Reasoning', 'English', 'General Awareness'])]} />
    <Panel><label className="flex items-start gap-3"><input type="checkbox" checked={withTest} onChange={(e) => setWithTest(e.target.checked)} className="mt-0.5 h-4 w-4 rounded border-line text-brand-600" /><span><span className="block text-sm font-medium text-ink">Create online test from this paper</span><span className="block text-xs text-ink-muted">Add questions to create an online test. A PDF is optional.</span></span></label>{withTest && <div className="mt-5 border-t border-line pt-5"><div className="flex items-center justify-between gap-3"><Field label="Duration (minutes)"><Input required type="number" min="1" value={draft.duration} onChange={(e) => set('duration', e.target.value)} /></Field><Button type="button" variant="secondary" size="sm" onClick={() => setQuestions((items) => [...items, blankQuestion()])}><PlusIcon className="h-4 w-4" /> Add question</Button></div><div className="mt-4 space-y-4">{questions.map((question, index) => <div key={question.key} className="rounded-xl border border-line p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-ink">Question {index + 1}</p><button type="button" disabled={questions.length === 1} onClick={() => setQuestions((items) => items.filter((item) => item.key !== question.key))} className="text-ink-muted hover:text-red-600 disabled:opacity-40"><Trash2Icon className="h-4 w-4" /></button></div><div className="mt-3 grid gap-3"><Textarea required rows={2} value={question.text} onChange={(e) => updateQuestion(question.key, { text: e.target.value })} placeholder="Question text" /><div className="grid gap-2 sm:grid-cols-2">{question.options.map((option, optionIndex) => <div key={optionIndex} className="flex items-center gap-2"><Input required value={option} onChange={(e) => updateQuestion(question.key, { options: question.options.map((item, i) => i === optionIndex ? e.target.value : item) })} placeholder={`Option ${String.fromCharCode(65 + optionIndex)}`} /><button type="button" onClick={() => updateQuestion(question.key, { correctAnswer: optionIndex })} className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${question.correctAnswer === optionIndex ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-line text-ink-muted'}`}><CheckIcon className="h-4 w-4" /></button></div>)}</div><Textarea rows={2} value={question.explanation} onChange={(e) => updateQuestion(question.key, { explanation: e.target.value })} placeholder="Answer explanation" /><div className="grid gap-3 sm:grid-cols-2"><Field label="Marks"><Input required type="number" min="0" step="0.25" value={question.marks} onChange={(e) => updateQuestion(question.key, { marks: Number(e.target.value) })} /></Field><Field label="Negative marks"><Input required type="number" min="0" step="0.25" value={question.negativeMarks} onChange={(e) => updateQuestion(question.key, { negativeMarks: Number(e.target.value) })} /></Field></div></div></div>)}</div></div>}</Panel>
    {error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Link to="/admin/previous-papers" className={btn('secondary', 'md')}>Cancel</Link><Button type="submit" disabled={saving || (!editing && !draft.file && !withTest)}>{saving ? 'Saving…' : editing ? 'Update paper' : 'Save paper'}</Button></div></form></PageShell>;
}
