import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { BookOpenIcon, FileQuestionIcon, ListChecksIcon, PlusIcon, TargetIcon, UsersIcon } from 'lucide-react';
import { PageShell, Panel, StatCard } from '../../components/ui/PageShell';
import { btn } from '../../components/ui/Primitives';
import { fetchAdminDashboard } from '../../services/dashboard/dashboard.slice';
import type { AppDispatch, RootState } from '../../store';
export function AdminDashboard() { const dispatch = useDispatch<AppDispatch>(); const { admin: data, loading, error } = useSelector((s: RootState) => s.dashboard); useEffect(() => { dispatch(fetchAdminDashboard()); }, [dispatch]); const stats = data?.stats || {}; return <PageShell title="Dashboard" subtitle="Content, students and activity across Chandrabhaga Academy." width="max-w-[1400px]" actions={<Link to="/admin/courses/new" className={btn('primary', 'md')}><PlusIcon className="h-4 w-4" /> Create Course</Link>}>{error && <p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><StatCard label="Students" value={String(stats.students || 0)} icon={<UsersIcon className="h-4 w-4" />} /><StatCard label="Courses" value={String(stats.courses || 0)} hint={`${stats.courseDrafts || 0} drafts`} icon={<BookOpenIcon className="h-4 w-4" />} /><StatCard label="Test series" value={String(stats.testSeries || 0)} icon={<ListChecksIcon className="h-4 w-4" />} /><StatCard label="Tests" value={String(stats.tests || 0)} icon={<FileQuestionIcon className="h-4 w-4" />} /><StatCard label="Questions" value={String(stats.questions || 0)} icon={<FileQuestionIcon className="h-4 w-4" />} /><StatCard label="Attempts" value={String(stats.attempts || 0)} icon={<TargetIcon className="h-4 w-4" />} /></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Panel><h2 className="font-semibold text-ink">Recent activity</h2><div className="mt-4 divide-y divide-line">{loading ? <p className="py-4 text-sm text-ink-muted">Loading...</p> : !data?.recentActivity?.length ? <p className="py-4 text-sm text-ink-muted">No recent activity.</p> : data.recentActivity.map((item: any) => <div key={item.id} className="flex justify-between gap-4 py-3 text-sm"><span>{item.text}</span><span className="shrink-0 text-xs text-ink-muted">{new Date(item.date).toLocaleDateString('en-IN')}</span></div>)}</div></Panel><Panel><h2 className="font-semibold text-ink">Quick actions</h2><div className="mt-4 grid gap-2">{[['Create Course','/admin/courses/new'],['Create Test Series','/admin/test-series/new'],['Upload Notes','/admin/notes/new'],['Add Current Affairs','/admin/current-affairs/new'],['Upload Syllabus','/admin/syllabus/new']].map(([label,to]) => <Link key={to} to={to} className={btn('secondary','md','justify-start')}>{label}</Link>)}</div></Panel></div></PageShell>; }
